export type DocsErrorSeverity = 'critical' | 'error' | 'warning' | 'info';

export type DocsErrorItem = {
  code: string;
  message: string;
  severity: DocsErrorSeverity;
  category: string;
  location: string;
  cause: string;
  solution: string;
  steps?: string[];
  relatedCodes?: string[];
};

export type DocsErrorCategory = {
  id: string;
  name: string;
  description: string;
  errors: DocsErrorItem[];
};

export type DocsButtonItem = {
  name: string;
  description: string;
};

export type DocsParamItem = {
  name: string;
  description: string;
  tips?: string;
};

export type DocsToolSection = {
  id: string;
  title: string;
  overview: string;
  buttons: DocsButtonItem[];
  parameters: DocsParamItem[];
  errors: DocsErrorItem[];
};

export type DocsContent = {
  intro: string;
  tools: DocsToolSection[];
  errorDictionary: DocsErrorCategory[];
};

export const docsContentZh: DocsContent = {
  intro: `欢迎使用 Original Character Maker 用户手册！

本手册涵盖全部 7 个功能模块的详细说明，以及一份全局错误字典。当你在某个工具中遇到报错或不清楚某个按钮/参数的作用时，可以打开本手册查阅对应的章节。

手册结构：
· 工具手册 — 每个工具独立成章，包含功能概述、按钮讲解、参数说明、报错与解决
· 错误字典 — 按分类（A~Z、0~9）编排的全局错误索引，像查字典一样快速定位

错误字典使用指南：
1. 先看错误面板上显示的 Code（如 STYLE_TRANSFER_REQUEST_FAILED）
2. 按首字母找到对应分类（S → 系统与工作流）
3. 在分类内按字典顺序找到该条目
4. 阅读「位置」确认你在哪个页面、哪个区域遇到了这个错误
5. 按照「解决步骤」逐一排查`,

  tools: [
    {
      id: 'face-maker',
      title: '捏脸编辑器',
      overview: `捏脸编辑器是 OC Maker 的入门级工具，通过左侧部件资产库选择发型、眼型、眉型、鼻型、嘴型、脸型、耳朵和配件，再通过右侧 16 个数值滑块精细调整比例、颜色和位置，最终在中央画布实时预览角色形象。所有调整都在本地完成，不会上传任何图片或数据。`,
      buttons: [
        { name: '保存草稿', description: '将当前所有部件选择和参数值保存到浏览器本地存储。保存成功后状态指示器会从黄色「未保存」变为绿色「已保存」。' },
        { name: '导出', description: '将当前捏脸配置导出为 JSON 文件（oc-face-maker-config.json），包含全部部件和参数值，可分享给他人或备份。' },
        { name: '导入配置', description: '选择之前导出的 JSON 配置文件，恢复部件选择和参数值。导入后会自动覆盖当前画布。' },
        { name: '重刷', description: '将所有参数重置为默认值，部件恢复为初始状态。操作前会弹出二次确认弹窗防止误触。' },
        { name: '返回首页', description: '离开捏脸编辑器回到主页。如果当前有未保存的修改，会先弹出确认弹窗。' },
        { name: '打开设置', description: '打开全局设置面板，可调整主题、语言、音频、API 等。' },
      ],
      parameters: [
        { name: '头部比例', description: '调整头部整体大小，范围 80~120。数值越大头部越显大。', tips: '建议配合脸长一起调整，避免头身比例失衡。' },
        { name: '脸长', description: '调整脸部长度，范围 80~120。影响整体脸型从圆脸到长脸的过渡。' },
        { name: '下巴宽度', description: '调整下巴宽窄，范围 80~120。数值小则下巴尖，数值大则下巴宽。' },
        { name: '额头高度', description: '调整额头占脸部的比例，范围 80~120。' },
        { name: '肤色', description: '通过颜色选择器调整角色皮肤色调。' },
        { name: '发色', description: '调整头发颜色，支持任意 HEX 颜色值。' },
        { name: '眉距', description: '调整两眉之间的距离，范围 80~120。' },
        { name: '眼睛大小', description: '调整眼睛整体缩放比例，范围 80~120。' },
        { name: '眼距', description: '调整两眼之间的距离，范围 80~120。' },
        { name: '眼位', description: '调整眼睛在面部的垂直位置，范围 80~120。数值大则眼睛偏上。' },
        { name: '瞳色', description: '调整瞳孔颜色。' },
        { name: '鼻高', description: '调整鼻子长度/高度，范围 80~120。' },
        { name: '嘴角弧度', description: '调整嘴角上扬或下垂程度，范围 80~120。数值大则嘴角上扬（微笑）。' },
        { name: '嘴宽', description: '调整嘴巴宽度，范围 80~120。' },
        { name: '配件颜色', description: '当选择眼镜、发饰等配件时，调整配件的颜色。' },
        { name: '整体倾角', description: '微调整个面部的轻微倾斜角度，范围 -10~10 度。' },
      ],
      errors: [
        {
          code: 'CONFIG_CORRUPTED',
          message: '捏脸配置加载异常，画布显示不完整或参数滑块无法拖动',
          severity: 'error',
          category: 'B. 配置与数据',
          location: '页面：捏脸编辑器 → 区域：中央画布 / 右侧参数面板',
          cause: '浏览器 localStorage 中保存的 face-maker 配置数据损坏，可能由浏览器更新、手动清理数据、或跨版本导入不兼容的配置导致。',
          solution: '重置配置并重新捏脸。',
          steps: [
            '点击左下角的「重刷」按钮',
            '在弹出的确认弹窗中点击「确认重刷」',
            '如果重刷后仍然异常，按 Ctrl+Shift+I 打开开发者工具 → Application → Local Storage → 删除以 face-maker 开头的键',
            '刷新页面后重新开始',
          ],
          relatedCodes: ['IMPORT_INVALID_JSON', 'STORAGE_READ_ONLY'],
        },
        {
          code: 'IMPORT_INVALID_JSON',
          message: '导入配置时提示「无效的 JSON 格式」',
          severity: 'warning',
          category: 'B. 配置与数据',
          location: '页面：捏脸编辑器 → 区域：左下角「导入配置」按钮',
          cause: '文件内容损坏、不是 JSON 格式、或被其他程序修改过。也可能选择了非 face-maker 导出的配置文件。',
          solution: '检查文件有效性并重新导入。',
          steps: [
            '用文本编辑器打开要导入的 JSON 文件',
            '确认文件顶部包含 "tool": "face-maker"',
            '确认文件是有效的 UTF-8 编码，无乱码',
            '如果文件损坏，尝试从历史备份中恢复',
          ],
          relatedCodes: ['IMPORT_TOOL_MISMATCH', 'CONFIG_CORRUPTED'],
        },
        {
          code: 'IMPORT_TOOL_MISMATCH',
          message: '导入配置时提示「工具类型不匹配」',
          severity: 'warning',
          category: 'B. 配置与数据',
          location: '页面：捏脸编辑器 → 区域：左下角「导入配置」按钮',
          cause: '导入的 JSON 文件中 tool 字段不是 face-maker，可能是其他工具的配置文件。',
          solution: '确认导入的文件是从捏脸编辑器的「导出」按钮生成的 JSON。',
          steps: [
            '用文本编辑器打开要导入的 JSON 文件',
            '确认文件顶部包含 "tool": "face-maker"',
            '如果不是，找到正确的 face-maker 配置文件再导入',
            '或从其他工具页面导入该文件',
          ],
          relatedCodes: ['IMPORT_INVALID_JSON'],
        },
        {
          code: 'LOCAL_STORAGE_FULL',
          message: '保存失败，提示浏览器存储空间不足',
          severity: 'error',
          category: 'B. 配置与数据',
          location: '页面：捏脸编辑器 → 区域：左下角「保存草稿」按钮',
          cause: '浏览器 localStorage 存储空间已满（通常约 5~10MB）。可能保存了大量图片数据或其他工具的历史记录。',
          solution: '清理浏览器存储空间或导出配置到本地文件。',
          steps: [
            '先点击「导出」按钮将当前配置备份到本地文件',
            '按 Ctrl+Shift+I 打开开发者工具 → Application → Local Storage',
            '删除不再需要的键（尤其是包含图片 base64 的大键）',
            '返回捏脸编辑器重新点击「保存草稿」',
          ],
          relatedCodes: ['STORAGE_READ_ONLY'],
        },
        {
          code: 'STORAGE_READ_ONLY',
          message: '保存操作无反应，刷新后数据丢失',
          severity: 'critical',
          category: 'B. 配置与数据',
          location: '页面：捏脸编辑器 → 区域：左下角「保存草稿」按钮',
          cause: '浏览器处于隐私/无痕模式，或 localStorage 被系统策略禁用，或磁盘空间已满导致浏览器将存储设为只读。',
          solution: '退出隐私模式或释放磁盘空间。',
          steps: [
            '确认浏览器不在无痕/隐私浏览模式（该模式通常禁用 localStorage）',
            '检查系统磁盘空间是否已满',
            '尝试在普通窗口中重新打开应用',
            '如果问题持续，使用「导出」功能将配置保存为本地文件作为替代方案',
          ],
          relatedCodes: ['LOCAL_STORAGE_FULL'],
        },
        {
          code: 'UNSAVED_WARNING',
          message: '返回首页时提示「你还没保存当前捏脸项目」',
          severity: 'info',
          category: 'B. 配置与数据',
          location: '页面：捏脸编辑器 → 区域：左上角「返回首页」按钮',
          cause: '当前画布状态与上次保存的快照不一致（isDirty 为 true）。你可能修改了参数但忘记保存。',
          solution: '根据需要选择保存或放弃。',
          steps: [
            '如果希望保留修改：点击弹窗中的「取消」，回到编辑器点击「保存草稿」，然后再返回首页',
            '如果不需要保留：点击弹窗中的「确认返回」',
          ],
        },
      ],
    },
    {
      id: 'style-transfer',
      title: '转画风',
      overview: `转画风工具用于将角色图像转换为指定画风。上传 PNG/JPG 格式的角色图像后，通过选择 AI 模型、编写 Prompt 和调整高级参数，调用后端 API 进行风格转换。支持自动抠图、配色保持、姿势保留、面部锁定等高级功能。本工具需要联网并配置有效的 API Key 才能使用。`,
      buttons: [
        { name: '选择图片 / 替换图片', description: '上传角色图像文件。支持 PNG 和 JPG 格式，推荐上传单人立绘或清晰半身图。' },
        { name: '开始', description: '启动风格转换流程。会先验证输入文件和参数，然后向后端发送转换请求。' },
        { name: '复制 JSON', description: '将当前所有参数配置复制为 JSON 文本到剪贴板，方便分享或备份。' },
        { name: '下载 JSON', description: '将当前参数配置下载为 JSON 文件。' },
        { name: '复制结果', description: '转换成功后，将结果图片复制到剪贴板（如果浏览器支持）。' },
        { name: '下载结果', description: '将转换后的结果图片下载到本地。' },
        { name: '复制错误', description: '转换失败时，将错误详情 JSON 复制到剪贴板，便于排查问题。' },
        { name: '下载错误', description: '将错误详情下载为 JSON 文件。' },
        { name: '展开详情 / 收起详情', description: '展开或折叠高级参数面板、Prompt 预览面板和调试信息面板。' },
        { name: '重刷', description: '重置所有参数为默认值，清除上传的图片和结果。' },
      ],
      parameters: [
        { name: '模型', description: '选择使用的 AI 图像生成模型。内置模式走 Plato 后端通道，自定义模式使用你配置的外部 API。', tips: 'gpt-image-2 是默认推荐模型，支持编辑和生成；claude-4-sonnet 在角色一致性方面表现更好。' },
        { name: 'Prompt', description: '正面提示词，描述你想要的画风、场景和角色特征。支持使用「正面提示词库」快速插入常用 Tag。', tips: 'Prompt 会自动附加高级参数转换后的英文后缀，可在「Effective Prompt Preview」中查看最终效果。' },
        { name: 'Negative Prompt', description: '负面提示词，描述你不希望出现的内容。支持使用「负面提示词库」快速插入。', tips: '常见负面 Tag：低质量、多余手指、变形身体、模糊等。' },
        { name: 'Temperature', description: '采样温度，控制生成结果的随机性。范围 0~2，默认 0.7。', tips: '值越低结果越稳定可预测，值越高越有创意但可能偏离预期。' },
        { name: 'Steps', description: '去噪步数，范围 10~50。步数越多细节越丰富但耗时越长。' },
        { name: 'Strength', description: '风格强度/重绘幅度，范围 0~1。值越大原始图像保留越少，画风改变越彻底。', tips: '0.4~0.6 是常用区间，既能改变画风又能保留角色特征。' },
        { name: 'CFG', description: 'Classifier-Free Guidance 缩放因子，范围 1~20。值越大 Prompt 约束力越强。', tips: '7~12 是安全区间，过高会导致画面失真。' },
        { name: '需要抠图', description: '是否在转换前自动移除背景。启用后只保留角色主体进行风格转换。' },
        { name: '保持配色', description: '是否强制保留原始图像的配色方案。' },
        { name: '保留姿势', description: '是否尽量保持原始角色的姿势和构图。' },
        { name: '面部锁定', description: '是否使用面部特征锁定技术，确保转换后角色面部一致性。' },
        { name: '细节增强', description: '是否启用细节增强处理，提升输出图像的精细度。' },
        { name: '宽高比', description: '输出图像的宽高比例预设（1:1、2:3、3:2、16:9 等）。' },
        { name: '图像尺寸', description: '输出图像的短边像素数。' },
        { name: '线稿风格', description: '输出图像的线稿处理风格（无、精细、粗犷、水彩等）。' },
        { name: '配色方案', description: '强制应用的配色主题（暖色、冷色、pastel、高对比等）。' },
        { name: '背景类型', description: '背景处理方式（透明、纯色、渐变、场景、自然等）。' },
        { name: '光照风格', description: '场景光照效果（柔和、戏剧化、背光、伦勃朗等）。' },
      ],
      errors: [
        {
          code: 'API_KEY_MISSING',
          message: '点击「开始」后立刻报错，错误面板显示 API Key 相关错误',
          severity: 'critical',
          category: 'A. API 与网络',
          location: '页面：转画风 → 区域：左栏底部错误面板',
          cause: '未在「设置 → API」中配置 API Key，或 Key 被清空。转画风工具需要有效的 API Key 才能调用后端图像生成服务。',
          solution: '在设置面板中配置有效的 API Key。',
          steps: [
            '点击右上角「打开设置」或按对应快捷键',
            '切换到「API」标签页',
            '在「API Key」输入框中填入你的有效 Key',
            '点击「保存」后关闭设置面板',
            '返回转画风页面重新点击「开始」',
          ],
          relatedCodes: ['API_KEY_EXPIRED', '401_UNAUTHORIZED'],
        },
        {
          code: 'API_KEY_EXPIRED',
          message: '转换请求返回 401 或提示 Key 无效',
          severity: 'critical',
          category: 'A. API 与网络',
          location: '页面：转画风 → 区域：左栏底部错误面板',
          cause: '配置的 API Key 已过期、被吊销、或额度已用完。',
          solution: '更换有效的 API Key。',
          steps: [
            '打开「设置 → API」面板',
            '删除当前 Key，填入新的有效 Key',
            '如果不确定 Key 是否有效，可在 LLM Hub 的实时测试面板中先测试',
            '保存后返回转画风重试',
          ],
          relatedCodes: ['API_KEY_MISSING', '401_UNAUTHORIZED'],
        },
        {
          code: 'API_TIMEOUT',
          message: '请求长时间无响应，最终提示超时',
          severity: 'error',
          category: 'A. API 与网络',
          location: '页面：转画风 → 区域：左栏底部错误面板 / 进度条',
          cause: '后端生成耗时过长，超过了前端设置的超时时间。可能原因：图像尺寸过大、模型负载高、网络延迟高。',
          solution: '降低图像尺寸或检查网络连接。',
          steps: [
            '在「高级参数」中降低「图像尺寸」（建议不超过 2048）',
            '降低「Steps」值（建议 20~30）',
            '检查网络连接是否稳定',
            '如果使用的是自定义 API，确认后端服务器状态正常',
            '重试转换',
          ],
          relatedCodes: ['NETWORK_TIMEOUT', 'BACKEND_UNAVAILABLE'],
        },
        {
          code: 'BACKEND_UNAVAILABLE',
          message: '提示「后端不可用」或「无法连接到服务器」',
          severity: 'critical',
          category: 'A. API 与网络',
          location: '页面：转画风 → 区域：左栏底部错误面板',
          cause: '后端服务器未启动、崩溃、或前端配置的 API Base URL 不正确。',
          solution: '检查后端服务状态和 API 配置。',
          steps: [
            '打开浏览器开发者工具 → Network 标签页',
            '重新点击「开始」，观察请求是否发出以及响应状态码',
            '如果请求未发出，检查「设置 → API → API Base URL」是否正确',
            '如果请求返回 502/503，联系后端管理员确认服务状态',
            '如果是本地部署，确认后端进程是否在运行（npm start）',
          ],
          relatedCodes: ['NETWORK_DISCONNECTED', '502_BAD_GATEWAY', '503_SERVICE_UNAVAILABLE'],
        },
        {
          code: 'NETWORK_DISCONNECTED',
          message: '提示网络断开或无法访问互联网',
          severity: 'critical',
          category: 'A. API 与网络',
          location: '页面：转画风 → 区域：左栏底部错误面板',
          cause: '设备未连接网络、Wi-Fi 断开、或防火墙阻止了请求。',
          solution: '恢复网络连接。',
          steps: [
            '检查设备的网络连接状态',
            '尝试访问其他网站确认网络是否正常',
            '如果使用代理/VPN，检查代理设置是否正确',
            '如果是公司/校园网络，确认是否限制了 API 访问',
          ],
          relatedCodes: ['BACKEND_UNAVAILABLE', 'API_TIMEOUT'],
        },
        {
          code: 'FILE_FORMAT_UNSUPPORTED',
          message: '上传时提示「不支持的文件格式」',
          severity: 'warning',
          category: 'C. 文件与输入',
          location: '页面：转画风 → 区域：左栏「选择图片」按钮',
          cause: '选择了 WEBP、GIF、BMP、TIFF 或其他不支持的格式。转画风仅支持 PNG 和 JPG。',
          solution: '将图片转换为 PNG 或 JPG 格式。',
          steps: [
            '使用图片转换工具（主页 → 图片格式转换）将文件转为 PNG 或 JPG',
            '或使用系统自带的图片预览/编辑工具导出为 PNG/JPG',
            '重新在转画风页面选择转换后的文件',
          ],
          relatedCodes: ['FILE_CORRUPTED', 'UPLOAD_FORMAT'],
        },
        {
          code: 'FILE_TOO_LARGE',
          message: '上传后图片无法预览或转换时报内存错误',
          severity: 'warning',
          category: 'C. 文件与输入',
          location: '页面：转画风 → 区域：左栏预览区',
          cause: '上传的图片尺寸过大（超过 4096x4096 像素）或文件大小超过浏览器/后端限制。',
          solution: '压缩或缩小图片后再上传。',
          steps: [
            '使用图片转换工具将图片最大边缩放到 2048 或 4096 像素以下',
            '如果是 PNG，可转为 JPG 以减小文件大小',
            '重新上传处理后的图片',
          ],
          relatedCodes: ['DEVICE_MEMORY_LOW', 'FILE_FORMAT_UNSUPPORTED'],
        },
        {
          code: 'FILE_CORRUPTED',
          message: '图片预览显示空白或损坏',
          severity: 'warning',
          category: 'C. 文件与输入',
          location: '页面：转画风 → 区域：左栏预览区',
          cause: '图片文件本身已损坏，或下载过程中数据不完整。',
          solution: '使用其他图片或修复/重新下载该图片。',
          steps: [
            '尝试在系统图片查看器中打开该文件，确认是否能正常显示',
            '如果无法显示，尝试用图片修复工具或重新下载/导出',
            '更换为其他有效的 PNG/JPG 图片',
          ],
          relatedCodes: ['FILE_FORMAT_UNSUPPORTED', 'UPLOAD_FORMAT'],
        },
        {
          code: 'MODEL_NOT_FOUND',
          message: '错误面板显示「模型不可用」或 404',
          severity: 'error',
          category: 'D. 模型与生成',
          location: '页面：转画风 → 区域：左栏底部错误面板',
          cause: '选择的模型在后端不存在、已被下架、或当前 API Key 无权访问该模型。',
          solution: '切换到其他可用模型。',
          steps: [
            '在「模型」下拉框中选择其他模型（如 gpt-image-2）',
            '如果使用自定义 API，确认模型 ID 拼写正确',
            '在「设置 → API」中确认当前 Key 支持所选模型',
            '重试转换',
          ],
          relatedCodes: ['403_FORBIDDEN', 'API_KEY_EXPIRED'],
        },
        {
          code: 'PROMPT_BLOCKED',
          message: '请求被拦截，提示「内容策略违规」或「sensitive words」',
          severity: 'error',
          category: 'D. 模型与生成',
          location: '页面：转画风 → 区域：左栏底部错误面板',
          cause: 'Prompt 或 Negative Prompt 中包含了后端服务商的安全过滤器拦截的词汇。即使是正常的艺术创作词汇，某些平台也会误判。',
          solution: '修改 Prompt，移除或替换可能触发过滤器的词汇。',
          steps: [
            '查看错误详情中的具体提示信息，找出被拦截的关键词',
            '将敏感词汇用同义词替换或删除',
            '简化 Prompt，先使用最基础的描述测试是否能通过',
            '逐步添加修饰词，找出具体触发拦截的词汇',
          ],
          relatedCodes: ['403_FORBIDDEN'],
        },
        {
          code: 'PROMPT_TOO_LONG',
          message: '提示 Prompt 超出长度限制',
          severity: 'warning',
          category: 'D. 模型与生成',
          location: '页面：转画风 → 区域：Prompt 输入框 / 左栏底部错误面板',
          cause: 'Prompt + 高级参数自动附加的后缀总长度超过了后端模型的最大输入限制。',
          solution: '缩短 Prompt 或减少高级参数。',
          steps: [
            '在「Effective Prompt Preview」中查看最终拼接的完整 Prompt 长度',
            '精简正面 Prompt，删除冗余描述',
            '减少高级参数的数量（每个参数都会附加英文后缀）',
            '重试',
          ],
          relatedCodes: ['MODEL_NOT_FOUND'],
        },
        {
          code: 'STYLE_TRANSFER_INPUT_MISSING',
          message: '点击「开始」后立刻报错，提示未上传图片',
          severity: 'warning',
          category: 'C. 文件与输入',
          location: '页面：转画风 → 区域：左栏底部错误面板',
          cause: '未上传图片，或上传后点击了「开始」但没有有效的输入文件。',
          solution: '确认已上传有效的图片文件。',
          steps: [
            '点击「选择图片」按钮',
            '在文件选择器中选择有效的 PNG/JPG 文件',
            '确认预览区显示了图片缩略图',
            '点击「开始」',
          ],
          relatedCodes: ['FILE_FORMAT_UNSUPPORTED', 'FILE_CORRUPTED'],
        },
        {
          code: 'STYLE_TRANSFER_REQUEST_FAILED',
          message: '错误面板上显示「STYLE_TRANSFER_REQUEST_FAILED」',
          severity: 'error',
          category: 'A. API 与网络',
          location: '页面：转画风 → 区域：左栏底部错误面板',
          cause: '后端 API 请求失败。可能是网络中断、API Key 无效、模型不可用、或服务器内部错误。',
          solution: '根据错误详情中的具体信息排查。',
          steps: [
            '展开错误面板查看详细错误信息（HTTP 状态码、后端返回的消息）',
            '如果是 401：检查 API Key 是否有效',
            '如果是 404：检查模型是否可用',
            '如果是 429：等待一段时间后重试，或降低请求频率',
            '如果是 500/502/503：检查后端服务状态',
            '如果是网络错误：检查网络连接',
          ],
          relatedCodes: ['API_KEY_MISSING', 'API_KEY_EXPIRED', 'MODEL_NOT_FOUND', 'BACKEND_UNAVAILABLE', '429_TOO_MANY_REQUESTS'],
        },
        {
          code: '429_TOO_MANY_REQUESTS',
          message: '提示请求过于频繁（Rate Limit）',
          severity: 'warning',
          category: 'A. API 与网络',
          location: '页面：转画风 → 区域：左栏底部错误面板',
          cause: '短时间内发送了过多请求，超过了服务商的速率限制。',
          solution: '等待一段时间后重试。',
          steps: [
            '查看错误详情中的 Retry-After 提示（如果有）',
            '等待 30~60 秒后重试',
            '如果频繁遇到此问题，降低同时进行的操作数量',
            '考虑升级 API 套餐以获得更高的速率限制',
          ],
          relatedCodes: ['API_RATE_LIMIT', 'STYLE_TRANSFER_REQUEST_FAILED'],
        },
        {
          code: '500_INTERNAL_ERROR',
          message: '后端返回 500 内部服务器错误',
          severity: 'error',
          category: '0~9. HTTP 状态码',
          location: '页面：转画风 → 区域：左栏底部错误面板',
          cause: '后端服务在处理请求时发生内部异常。可能是模型加载失败、GPU 内存不足、或代码 Bug。',
          solution: '稍后重试或联系后端管理员。',
          steps: [
            '等待 1~2 分钟后重试',
            '降低图像尺寸和 Steps 值，减少后端负载',
            '如果问题持续，联系后端管理员查看服务器日志',
          ],
          relatedCodes: ['502_BAD_GATEWAY', '503_SERVICE_UNAVAILABLE'],
        },
        {
          code: '502_BAD_GATEWAY',
          message: '后端返回 502 Bad Gateway',
          severity: 'error',
          category: '0~9. HTTP 状态码',
          location: '页面：转画风 → 区域：左栏底部错误面板',
          cause: '反向代理（如 Nginx）无法连接到后端应用服务器。可能是后端进程崩溃或未启动。',
          solution: '检查后端服务状态。',
          steps: [
            '如果是本地部署，确认后端进程是否在运行',
            '检查后端服务端口是否被占用',
            '查看后端日志确认是否有启动错误',
            '重启后端服务后重试',
          ],
          relatedCodes: ['503_SERVICE_UNAVAILABLE', 'BACKEND_UNAVAILABLE'],
        },
        {
          code: '503_SERVICE_UNAVAILABLE',
          message: '后端返回 503 Service Unavailable',
          severity: 'error',
          category: '0~9. HTTP 状态码',
          location: '页面：转画风 → 区域：左栏底部错误面板',
          cause: '后端服务暂时不可用，可能正在进行维护、重启、或过载保护。',
          solution: '稍后重试。',
          steps: [
            '等待 2~3 分钟后重试',
            '检查后端服务状态页面（如果有）',
            '联系后端管理员确认是否在维护',
          ],
          relatedCodes: ['502_BAD_GATEWAY', 'BACKEND_UNAVAILABLE'],
        },
        {
          code: 'IMPORT_INVALID_JSON',
          message: '导入配置时提示「无效的 JSON 格式」',
          severity: 'warning',
          category: 'B. 配置与数据',
          location: '页面：转画风 → 区域：顶部「导入配置」按钮',
          cause: '文件内容损坏、不是 JSON 格式、或被其他程序修改过。',
          solution: '检查文件是否为有效的 UTF-8 编码文本文件。',
          steps: [
            '用文本编辑器打开文件查看是否有乱码',
            '确认文件顶部包含 "tool": "style-transfer"',
            '尝试用 JSON 在线格式化工具验证',
          ],
          relatedCodes: ['IMPORT_TOOL_MISMATCH'],
        },
        {
          code: 'IMPORT_TOOL_MISMATCH',
          message: '导入配置时提示「工具类型不匹配」',
          severity: 'warning',
          category: 'B. 配置与数据',
          location: '页面：转画风 → 区域：顶部「导入配置」按钮',
          cause: '导入的 JSON 文件中 tool 字段不是 style-transfer。',
          solution: '确认导入的是转画风页面导出的配置文件。',
          steps: [
            '用文本编辑器打开文件',
            '确认 tool 字段值为 "style-transfer"',
            '如果不是，找到正确的配置文件或从对应工具页面导入',
          ],
          relatedCodes: ['IMPORT_INVALID_JSON'],
        },
        {
          code: 'DEVICE_MEMORY_LOW',
          message: '浏览器标签页崩溃或无响应',
          severity: 'critical',
          category: 'F. 系统与权限',
          location: '页面：转画风 → 区域：整个页面',
          cause: '设备内存不足，浏览器强制终止了标签页进程。通常发生在处理超大图片（>8K 分辨率）时。',
          solution: '关闭其他标签页，降低图片尺寸，或换用内存更大的设备。',
          steps: [
            '保存当前工作（如果有）',
            '关闭其他不用的浏览器标签页',
            '使用图片转换工具将图片最大边缩放到 2048 以下',
            '重启浏览器后重试',
            '如果问题持续，尝试在内存更大的设备上操作',
          ],
          relatedCodes: ['FILE_TOO_LARGE'],
        },
      ],
    },
    {
      id: 'prompt-suite',
      title: '角色设卡 / 世界观编辑',
      overview: `PromptSuite 是一个富文本编辑器，用于整理角色设定卡（Character Sheet）、世界观设定（World Bible）、关系图谱（Relationship Map）和语言风格档案（Speech Profile）。支持字体、颜色、高亮、标题、列表、表格、代码块、引用框、图片插入等丰富排版功能。所有内容自动保存到本地浏览器。`,
      buttons: [
        { name: '保存文档', description: '将当前编辑器中的 HTML 内容和工具栏状态保存到本地存储。' },
        { name: '重刷', description: '清空当前文档，恢复为默认模板。操作前会弹出二次确认。' },
        { name: '导入配置', description: '导入之前导出的 PromptSuite JSON 配置文件，恢复文档内容和工具栏状态。' },
        { name: '导出 HTML', description: '将当前文档导出为独立的 HTML 文件，包含内联样式，可直接在浏览器中打开查看。' },
        { name: '导出封装包', description: '将文档内容、LLM 配置和 TTS 配置打包导出为一个 JSON 文件，便于跨设备迁移。' },
        { name: '复制文本', description: '将当前文档的纯文本内容复制到剪贴板。' },
        { name: '展开详情 / 收起详情', description: '展开或折叠各工具栏分组（字体、样式、段落、插入、历史）。' },
        { name: '自定义字体', description: '打开弹窗输入系统中已安装的字体名称，应用到编辑器。' },
      ],
      parameters: [
        { name: '模板选择', description: '快速切换预设模板：世界观设定、角色设卡、关系图谱、语言风格档案、时间线。' },
        { name: '字体', description: '设置编辑器正文字体族。支持系统字体和自定义字体。' },
        { name: '字号', description: '设置基础字号，支持 px/rem 单位。' },
        { name: '文本颜色', description: '设置当前选中文本的颜色。' },
        { name: '高亮色', description: '设置当前选中文本的背景高亮颜色。' },
        { name: '块样式', description: '设置当前段落的全局块样式预设。' },
        { name: '行高', description: '调整段落行高倍率。' },
        { name: '加粗 / 斜体 / 下划线 / 删除线', description: '基础文本格式按钮，支持 Ctrl+Alt+B/I/U 等快捷键。' },
        { name: '下标 / 上标', description: '将选中文本转为下标或上标格式。' },
        { name: '引用块', description: '插入带有装饰性边框的引用块。' },
        { name: '代码 / 代码块', description: '插入行内代码或预格式化代码块。' },
        { name: '链接', description: '插入可点击的超链接。' },
        { name: '表格', description: '插入可编辑的 HTML 表格。' },
        { name: '图片', description: '插入图片（使用占位符链接）。' },
        { name: '强调框 / 详情折叠 / 徽章', description: '插入特殊样式的内容块，用于突出显示重要信息。' },
        { name: '清除格式', description: '移除当前选中文本的所有格式。' },
        { name: '撤销 / 重做', description: '撤销或重做最近的编辑操作。支持 Ctrl+Z / Ctrl+Y 快捷键。' },
      ],
      errors: [
        {
          code: 'CONFIG_CORRUPTED',
          message: '打开编辑器后内容空白或格式错乱',
          severity: 'error',
          category: 'B. 配置与数据',
          location: '页面：角色设卡 / 世界观编辑 → 区域：中央编辑器区域',
          cause: '浏览器 localStorage 中保存的 PromptSuite 配置数据损坏。',
          solution: '重刷编辑器或手动清理 localStorage。',
          steps: [
            '点击「重刷」按钮',
            '确认弹窗中点击「确认重刷」',
            '如果仍然异常，按 Ctrl+Shift+I → Application → Local Storage → 删除 prompt-suite 相关键',
            '刷新页面',
          ],
          relatedCodes: ['IMPORT_INVALID_JSON', 'STORAGE_READ_ONLY'],
        },
        {
          code: 'CURSOR_JUMP',
          message: '编辑时光标位置乱跳',
          severity: 'warning',
          category: 'F. 系统与权限',
          location: '页面：角色设卡 / 世界观编辑 → 区域：中央编辑器区域',
          cause: '早期版本中使用 dangerouslySetInnerHTML 实时重渲染导致 DOM 与 React 状态不同步。当前版本已修复。',
          solution: '刷新页面恢复自动保存内容。',
          steps: [
            '按 Ctrl+S 手动保存当前内容',
            '刷新页面（F5 或 Ctrl+R）',
            '页面加载后会自动恢复最近保存的内容',
          ],
        },
        {
          code: 'EXPORT_FAILED',
          message: '点击「导出 HTML」或「导出封装包」无反应',
          severity: 'error',
          category: 'F. 系统与权限',
          location: '页面：角色设卡 / 世界观编辑 → 区域：顶部导出按钮',
          cause: '浏览器阻止了下载弹窗，或文档内容过大导致 Blob 生成失败。',
          solution: '检查浏览器下载设置或分批导出。',
          steps: [
            '检查浏览器是否阻止了弹窗（地址栏右侧是否有弹窗拦截提示）',
            '允许当前网站的弹窗',
            '如果文档包含大量图片，尝试先移除部分图片再导出',
            '使用「复制文本」功能作为临时替代方案',
          ],
          relatedCodes: ['DEVICE_MEMORY_LOW'],
        },
        {
          code: 'IMPORT_INVALID_JSON',
          message: '导入配置时提示「无效的 JSON 格式」',
          severity: 'warning',
          category: 'B. 配置与数据',
          location: '页面：角色设卡 / 世界观编辑 → 区域：顶部「导入配置」按钮',
          cause: '文件内容损坏或格式不正确。',
          solution: '检查文件有效性。',
          steps: [
            '用文本编辑器打开文件',
            '确认文件顶部包含 "tool": "prompt-suite"',
            '用 JSON 在线格式化工具验证',
          ],
          relatedCodes: ['IMPORT_TOOL_MISMATCH'],
        },
        {
          code: 'IMPORT_TOOL_MISMATCH',
          message: '导入配置时提示「工具类型不匹配」',
          severity: 'warning',
          category: 'B. 配置与数据',
          location: '页面：角色设卡 / 世界观编辑 → 区域：顶部「导入配置」按钮',
          cause: '导入的 JSON 文件中 tool 字段不是 prompt-suite。',
          solution: '确认导入的是 PromptSuite 导出的配置文件。',
          steps: [
            '用文本编辑器打开文件',
            '确认 tool 字段值为 "prompt-suite"',
            '找到正确的文件后重新导入',
          ],
          relatedCodes: ['IMPORT_INVALID_JSON'],
        },
        {
          code: 'PASTE_FORMAT_LOSS',
          message: '从外部复制粘贴后格式丢失',
          severity: 'info',
          category: 'C. 文件与输入',
          location: '页面：角色设卡 / 世界观编辑 → 区域：中央编辑器区域',
          cause: '富文本编辑器对外部 HTML 的粘贴处理会过滤不安全的标签和样式，这是安全设计。',
          solution: '在编辑器内手动重建格式。',
          steps: [
            '粘贴纯文本内容',
            '使用编辑器的格式工具（加粗、颜色、标题等）重新应用格式',
            '对于表格，使用编辑器内置的表格插入工具重建',
          ],
        },
        {
          code: 'STORAGE_READ_ONLY',
          message: '保存无反应，刷新后内容丢失',
          severity: 'critical',
          category: 'B. 配置与数据',
          location: '页面：角色设卡 / 世界观编辑 → 区域：顶部「保存文档」按钮',
          cause: '浏览器处于隐私/无痕模式，或 localStorage 被禁用。',
          solution: '退出隐私模式，或使用导出功能备份。',
          steps: [
            '确认不在无痕浏览模式',
            '点击「导出 HTML」将内容保存到本地文件',
            '在普通窗口中重新打开应用',
            '导入之前导出的文件',
          ],
          relatedCodes: ['LOCAL_STORAGE_FULL'],
        },
        {
          code: 'LOCAL_STORAGE_FULL',
          message: '保存失败，提示存储空间不足',
          severity: 'error',
          category: 'B. 配置与数据',
          location: '页面：角色设卡 / 世界观编辑 → 区域：顶部「保存文档」按钮',
          cause: 'localStorage 已满。富文本文档可能很大，尤其是包含大量 HTML 标记时。',
          solution: '清理存储空间或导出到本地文件。',
          steps: [
            '先点击「导出 HTML」备份当前内容',
            '打开开发者工具 → Application → Local Storage',
            '删除其他工具不再需要的历史数据',
            '返回编辑器重新保存',
          ],
          relatedCodes: ['STORAGE_READ_ONLY', 'EXPORT_FAILED'],
        },
        {
          code: 'UNSAVED_WARNING',
          message: '返回首页时提示有未保存的修改',
          severity: 'info',
          category: 'B. 配置与数据',
          location: '页面：角色设卡 / 世界观编辑 → 区域：左上角「返回首页」按钮',
          cause: '当前文档与上次保存的快照不一致。',
          solution: '保存后再返回，或确认放弃修改。',
          steps: [
            '点击「保存文档」',
            '或点击「确认返回」放弃未保存的修改',
          ],
        },
      ],
    },
    {
      id: 'llm-hub',
      title: 'LLM 文本接入',
      overview: `LLM Hub 是大语言模型参数配置与实时测试工具。你可以在这里调整模型选择、采样参数、系统提示词等，然后通过实时测试面板与 AI 进行多轮对话，验证 Prompt 效果。支持保存多套配置预设，方便在不同创作场景间快速切换。内置模式走后端 /api/chat 代理，自定义模式直接调用你配置的外部 OpenAI 兼容 API。`,
      buttons: [
        { name: '保存文档', description: '将当前 LLM 配置保存到本地存储。' },
        { name: '重刷', description: '将所有参数重置为默认值。会弹出二次确认弹窗。' },
        { name: '导入配置', description: '导入之前导出的 LLM Hub JSON 配置文件。' },
        { name: '下载 JSON', description: '将当前 LLM 配置下载为 JSON 文件。' },
        { name: '参数 / 实时测试 / 预设', description: '三个模块切换按钮。参数面板调整模型配置；实时测试面板进行对话；预设面板管理配置快照。' },
        { name: '复制提示词', description: '将当前的系统提示词（System Prompt）复制到剪贴板。' },
        { name: '恢复为设置默认值', description: '从全局设置中读取默认的 LLM 配置并应用。' },
        { name: '发送', description: '在实时测试面板中发送输入的消息给 AI。' },
        { name: '清空', description: '清空当前对话历史和输出内容。' },
        { name: '保存为预设', description: '将当前所有参数保存为一个命名预设，方便后续快速加载。' },
        { name: '加载', description: '从已保存的预设中加载配置。' },
        { name: '删除', description: '删除已保存的预设。' },
      ],
      parameters: [
        { name: '模型', description: '选择使用的大语言模型。', tips: 'gpt-5.4 是默认推荐；gpt-5.4-mini 速度更快；claude-4-sonnet 在创意写作方面表现出色。' },
        { name: '温度 (Temperature)', description: '控制生成结果的随机性，范围 0~2。', tips: '创意写作建议 0.7~1.0；角色设定补全建议 0.3~0.5 以保证一致性。' },
        { name: 'Top P', description: '核采样参数，范围 0~1。控制候选词集合的大小。', tips: '通常与 Temperature 配合使用，默认 0.92 适合大多数场景。' },
        { name: '最大 Token 数', description: '单次响应的最大生成长度，范围 1~8192。', tips: '角色设定生成建议 1024~2048；短对话可设为 512。' },
        { name: '频率惩罚', description: '降低已出现词汇的重复概率，范围 -2~2。', tips: '正值可减少重复用词，负值可增加词汇多样性。' },
        { name: '存在惩罚', description: '降低整体重复主题的概率，范围 -2~2。', tips: '与频率惩罚配合使用，避免 AI 陷入循环表达。' },
        { name: '响应格式', description: '指定 AI 的输出格式：text（纯文本）或 json_object（强制 JSON）。', tips: '选择 json_object 时，Prompt 中需明确说明期望的 JSON 结构。' },
        { name: '随机种子', description: '固定随机种子以获得可复现的结果。设为 0 表示随机。', tips: '调试 Prompt 时固定种子，可以准确对比参数调整带来的效果差异。' },
        { name: 'Top K', description: '仅保留概率最高的 K 个候选词，范围 1~128。', tips: '部分模型不支持此参数，会被后端忽略。' },
        { name: '超时 (毫秒)', description: '单次请求的最大等待时间，范围 1000~120000。', tips: '网络不稳定时可适当增加，但过长会导致界面卡死感。' },
        { name: '重试次数', description: '请求失败时的自动重试次数，范围 0~5。', tips: '设为 2 可在网络波动时提高成功率。' },
        { name: '停止序列', description: '遇到指定文本时停止生成，多个序列用逗号分隔。', tips: '例如设为 "Human:,Assistant:" 可控制对话轮次切换。' },
        { name: '系统提示词', description: '定义 AI 的角色和行为准则的全局提示词。', tips: '这是影响输出质量最重要的参数。建议使用详细的角色设定和输出格式要求。' },
      ],
      errors: [
        {
          code: 'API_KEY_MISSING',
          message: '发送消息后立刻报错，提示 API Key 未配置',
          severity: 'critical',
          category: 'A. API 与网络',
          location: '页面：LLM 文本接入 → 区域：实时测试面板输出区',
          cause: '未在「设置 → API」中配置 API Key。LLM Hub 需要有效的 Key 才能调用大语言模型。',
          solution: '在设置面板中配置 API Key。',
          steps: [
            '点击右上角「打开设置」',
            '切换到「API」标签',
            '填入有效的 API Key',
            '保存并关闭设置',
            '返回 LLM Hub 重新发送消息',
          ],
          relatedCodes: ['API_KEY_EXPIRED', '401_UNAUTHORIZED'],
        },
        {
          code: 'API_KEY_EXPIRED',
          message: '请求返回 401 或提示 Key 无效',
          severity: 'critical',
          category: 'A. API 与网络',
          location: '页面：LLM 文本接入 → 区域：实时测试面板输出区',
          cause: 'API Key 已过期、被吊销或额度用完。',
          solution: '更换有效 Key。',
          steps: [
            '打开「设置 → API」',
            '替换为新的有效 Key',
            '保存后重试',
          ],
          relatedCodes: ['API_KEY_MISSING'],
        },
        {
          code: 'API_TIMEOUT',
          message: '发送消息后长时间无响应',
          severity: 'error',
          category: 'A. API 与网络',
          location: '页面：LLM 文本接入 → 区域：实时测试面板输出区',
          cause: '请求超时。可能是 Max Tokens 设置过大、网络延迟高、或模型负载高。',
          solution: '降低 Max Tokens 或增加超时时间。',
          steps: [
            '在参数面板中降低「最大 Token 数」（建议 1024 以下测试）',
            '增加「超时」值（建议 60000~120000）',
            '检查网络连接',
            '重试',
          ],
          relatedCodes: ['NETWORK_DISCONNECTED', 'API_TIMEOUT'],
        },
        {
          code: 'BACKEND_UNAVAILABLE',
          message: '提示后端不可用',
          severity: 'critical',
          category: 'A. API 与网络',
          location: '页面：LLM 文本接入 → 区域：实时测试面板输出区',
          cause: '后端服务未启动或 API Base URL 配置错误。',
          solution: '检查后端状态和配置。',
          steps: [
            '打开 Network 开发者工具',
            '重新发送消息，观察请求状态',
            '如果无请求发出，检查「设置 → API → API Base URL」',
            '如果返回 502/503，确认后端服务是否运行',
          ],
          relatedCodes: ['NETWORK_DISCONNECTED'],
        },
        {
          code: 'LLM_MODEL_UNAVAILABLE',
          message: '提示模型不可用',
          severity: 'error',
          category: 'D. 模型与生成',
          location: '页面：LLM 文本接入 → 区域：实时测试面板输出区',
          cause: '选择的模型在后端不存在或当前 Key 无权访问。',
          solution: '切换其他模型。',
          steps: [
            '在「模型」下拉框中选择其他模型',
            '确认模型 ID 拼写正确',
            '确认当前 Key 支持所选模型',
            '重试',
          ],
          relatedCodes: ['MODEL_NOT_FOUND', '403_FORBIDDEN'],
        },
        {
          code: 'LLM_TEST_ERROR',
          message: '实时测试面板显示「LLM_TEST_ERROR」',
          severity: 'error',
          category: 'D. 模型与生成',
          location: '页面：LLM 文本接入 → 区域：实时测试面板输出区',
          cause: 'API 请求失败。可能是网络问题、API Key 无效或过期、模型不可用、或请求超时。',
          solution: '根据错误详情排查。',
          steps: [
            '查看错误面板中的详细错误信息',
            '检查网络连接',
            '确认 API Key 有效',
            '尝试切换模型',
            '增加超时时间或减少 Max Tokens',
          ],
          relatedCodes: ['API_KEY_MISSING', 'API_KEY_EXPIRED', 'LLM_MODEL_UNAVAILABLE'],
        },
        {
          code: 'MODEL_NOT_FOUND',
          message: '后端返回 404，提示模型未找到',
          severity: 'error',
          category: 'D. 模型与生成',
          location: '页面：LLM 文本接入 → 区域：实时测试面板输出区',
          cause: '模型 ID 拼写错误或该模型已被下架。',
          solution: '更正模型 ID 或选择其他模型。',
          steps: [
            '检查「模型」输入框中的模型 ID 是否拼写正确',
            '从下拉列表中选择已知可用的模型',
            '如果使用自定义 API，查阅服务商文档确认模型列表',
            '重试',
          ],
          relatedCodes: ['LLM_MODEL_UNAVAILABLE'],
        },
        {
          code: 'PROMPT_BLOCKED',
          message: '内容被安全过滤器拦截',
          severity: 'error',
          category: 'D. 模型与生成',
          location: '页面：LLM 文本接入 → 区域：实时测试面板输出区',
          cause: '系统提示词或用户消息中包含被平台安全策略拦截的内容。',
          solution: '修改 Prompt 避免触发过滤器。',
          steps: [
            '查看错误详情中的提示信息',
            '修改系统提示词，移除可能触发过滤的描述',
            '简化测试消息，逐步排查触发词',
          ],
          relatedCodes: ['403_FORBIDDEN'],
        },
        {
          code: '429_TOO_MANY_REQUESTS',
          message: '请求过于频繁',
          severity: 'warning',
          category: 'A. API 与网络',
          location: '页面：LLM 文本接入 → 区域：实时测试面板输出区',
          cause: '短时间内发送了过多请求。',
          solution: '等待后重试。',
          steps: [
            '等待 30~60 秒',
            '降低测试频率',
            '重试',
          ],
          relatedCodes: ['API_RATE_LIMIT'],
        },
        {
          code: '500_INTERNAL_ERROR',
          message: '后端 500 错误',
          severity: 'error',
          category: '0~9. HTTP 状态码',
          location: '页面：LLM 文本接入 → 区域：实时测试面板输出区',
          cause: '后端内部异常。',
          solution: '稍后重试。',
          steps: [
            '等待 1~2 分钟',
            '降低 Max Tokens 重试',
            '如果持续失败，联系后端管理员',
          ],
          relatedCodes: ['502_BAD_GATEWAY', '503_SERVICE_UNAVAILABLE'],
        },
        {
          code: 'IMPORT_INVALID_CONFIG',
          message: '导入配置时提示「无效的配置数据」',
          severity: 'warning',
          category: 'B. 配置与数据',
          location: '页面：LLM 文本接入 → 区域：顶部「导入配置」按钮',
          cause: '导入的 JSON 中缺少 llmConfig 字段或格式不正确。',
          solution: '确认导入的是 LLM Hub 的配置文件。',
          steps: [
            '用文本编辑器打开文件',
            '确认包含 "tool": "llm-hub" 和 llmConfig 字段',
            '重新导入正确的文件',
          ],
          relatedCodes: ['IMPORT_INVALID_JSON', 'IMPORT_TOOL_MISMATCH'],
        },
        {
          code: 'IMPORT_INVALID_JSON',
          message: '导入配置时提示「无效的 JSON 格式」',
          severity: 'warning',
          category: 'B. 配置与数据',
          location: '页面：LLM 文本接入 → 区域：顶部「导入配置」按钮',
          cause: '文件损坏或格式不正确。',
          solution: '检查文件有效性。',
          steps: [
            '用文本编辑器打开文件',
            '用 JSON 在线格式化工具验证',
            '重新导入',
          ],
          relatedCodes: ['IMPORT_INVALID_CONFIG'],
        },
        {
          code: 'IMPORT_TOOL_MISMATCH',
          message: '导入配置时提示「工具类型不匹配」',
          severity: 'warning',
          category: 'B. 配置与数据',
          location: '页面：LLM 文本接入 → 区域：顶部「导入配置」按钮',
          cause: 'tool 字段不是 llm-hub。',
          solution: '确认导入正确的文件。',
          steps: [
            '用文本编辑器打开文件',
            '确认 tool 字段值为 "llm-hub"',
            '重新导入',
          ],
          relatedCodes: ['IMPORT_INVALID_JSON'],
        },
        {
          code: 'STORAGE_READ_ONLY',
          message: '保存无反应',
          severity: 'critical',
          category: 'B. 配置与数据',
          location: '页面：LLM 文本接入 → 区域：顶部「保存文档」按钮',
          cause: '浏览器无痕模式或 localStorage 被禁用。',
          solution: '退出无痕模式或使用导出备份。',
          steps: [
            '确认不在无痕模式',
            '点击「下载 JSON」备份配置',
            '在普通窗口中重新打开',
            '导入备份',
          ],
          relatedCodes: ['LOCAL_STORAGE_FULL'],
        },
        {
          code: 'LOCAL_STORAGE_FULL',
          message: '保存失败，存储空间不足',
          severity: 'error',
          category: 'B. 配置与数据',
          location: '页面：LLM 文本接入 → 区域：顶部「保存文档」按钮',
          cause: 'localStorage 已满。',
          solution: '清理存储或导出到文件。',
          steps: [
            '点击「下载 JSON」备份',
            '清理 localStorage 中其他工具的数据',
            '重新保存',
          ],
          relatedCodes: ['STORAGE_READ_ONLY'],
        },
      ],
    },
    {
      id: 'tts-export',
      title: 'TTS 语音导出',
      overview: `TTS 语音导出工具用于配置语音合成参数并生成角色语音素材。支持调整声音、语言、语速、音调、音量等基础参数，以及气息感、清晰度、表现力、停顿强度等高级参数。可上传参考音频作为音色克隆源，支持音频后处理（降噪、EQ、压缩）和发音精校（自定义替换规则）。`,
      buttons: [
        { name: '保存', description: '将当前 TTS 配置保存到本地存储。' },
        { name: '重刷', description: '将所有参数重置为默认值。会弹出二次确认。' },
        { name: '导入配置', description: '导入之前导出的 TTS JSON 配置文件。' },
        { name: '下载 JSON', description: '将当前 TTS 配置下载为 JSON 文件。' },
        { name: '展开 / 收起高级参数', description: '展开或折叠高级参数面板（停顿强度、语调曲线、强调模式）。' },
        { name: '展开 / 收起音频后处理', description: '展开或折叠音频后处理面板（降噪、EQ、压缩）。' },
        { name: '展开 / 收起发音精校', description: '展开或折叠发音精校面板（文本预处理、替换规则）。' },
      ],
      parameters: [
        { name: '声音', description: '选择预设的语音音色。', tips: 'Hanazora 是默认女声；Mirako 是元气女声；Rin 是少年声。' },
        { name: '语言', description: '合成语音的目标语言。', tips: '切换全局界面语言时，此字段会自动同步更新。' },
        { name: '语速', description: '语音播放速度倍率，范围 0.6~1.6。', tips: '1.0 是正常速度；角色情绪激动时可设为 1.2~1.4。' },
        { name: '情感', description: '描述期望的情感风格标签，如「温柔」「坚定」「忧郁」等。', tips: '部分后端模型支持情感标签，会被拼入合成提示词。' },
        { name: '音调', description: '音高偏移，范围 -12~12（半音单位）。', tips: '正值音调更高更明亮，负值更低沉。' },
        { name: '音量', description: '输出音量百分比，范围 40~140。', tips: '100 是原始音量；背景音较多时可设为 110~120。' },
        { name: '采样率', description: '输出音频的采样率（Hz）。', tips: '24000 是标准语音质量；44100/48000 提供更高音质但文件更大。' },
        { name: '气息感', description: '控制语音中的呼吸感强度，范围 0~100。', tips: '值越高越像真人自然呼吸，但过高会显得喘息。' },
        { name: '清晰度', description: '控制发音清晰度，范围 0~100。', tips: '值越高咬字越清晰，但可能显得机械。' },
        { name: '表现力', description: '控制情感表现力强度，范围 0~100。', tips: '值越高语调变化越丰富，适合戏剧性场景。' },
        { name: '语速变化', description: '控制语速的自然波动程度，范围 0~100。', tips: '值越高越像真人说话时的快慢变化。' },
        { name: '停顿强度', description: '控制句间停顿的长度，范围 0~100。', tips: '朗读诗歌或严肃内容时可适当提高。' },
        { name: '语调曲线', description: '预设的语调变化模式：平直、自然、戏剧化、旋律化。', tips: '「自然」适合日常对话；「戏剧化」适合动画配音；「旋律化」适合歌唱或朗诵。' },
        { name: '强调模式', description: '关键词强调强度：正常、强烈、微妙。', tips: '「强烈」会让 AI 在关键词处加重音；「微妙」则轻微提示。' },
        { name: '降噪', description: '输出音频的降噪强度，范围 0~100。', tips: '参考音频有背景噪音时可提高此值。' },
        { name: 'EQ 预设', description: '均衡器预设：平直、温暖、明亮、广播、清晰。', tips: '「温暖」适合叙事；「明亮」适合少女角色；「广播」适合旁白。' },
        { name: '压缩', description: '动态范围压缩强度，范围 0~100。', tips: '压缩可使音量更均匀，防止忽大忽小。' },
        { name: '后处理总开关', description: '是否启用音频后处理（降噪+EQ+压缩）。', tips: '关闭后处理可获得原始合成音质，但可能有底噪。' },
        { name: '文本预处理', description: '是否在合成前对文本进行标准化处理。', tips: '建议开启，可自动处理数字读法、英文缩写等。' },
        { name: '自定义替换规则', description: '输入替换规则，每行一条，格式为「原文=替换文」。', tips: '例如：「OC=欧西」会让合成时将「OC」读作「欧西」。' },
      ],
      errors: [
        {
          code: 'API_KEY_MISSING',
          message: '生成语音时提示 API Key 未配置',
          severity: 'critical',
          category: 'A. API 与网络',
          location: '页面：TTS 语音导出 → 区域：左栏输出区',
          cause: '未配置 API Key。',
          solution: '在设置面板配置 Key。',
          steps: [
            '打开「设置 → API」',
            '填入有效 Key',
            '保存后重试',
          ],
          relatedCodes: ['API_KEY_EXPIRED'],
        },
        {
          code: 'API_KEY_EXPIRED',
          message: '请求返回 401',
          severity: 'critical',
          category: 'A. API 与网络',
          location: '页面：TTS 语音导出 → 区域：左栏输出区',
          cause: 'Key 过期。',
          solution: '更换 Key。',
          steps: [
            '打开「设置 → API」',
            '替换为新的 Key',
            '保存后重试',
          ],
          relatedCodes: ['API_KEY_MISSING'],
        },
        {
          code: 'API_TIMEOUT',
          message: '请求超时',
          severity: 'error',
          category: 'A. API 与网络',
          location: '页面：TTS 语音导出 → 区域：左栏输出区',
          cause: '合成耗时过长。',
          solution: '缩短文本或增加超时。',
          steps: [
            '减少待合成文本长度',
            '增加超时设置',
            '重试',
          ],
          relatedCodes: ['NETWORK_DISCONNECTED'],
        },
        {
          code: 'BACKEND_UNAVAILABLE',
          message: '后端不可用',
          severity: 'critical',
          category: 'A. API 与网络',
          location: '页面：TTS 语音导出 → 区域：左栏输出区',
          cause: '后端未启动或配置错误。',
          solution: '检查后端状态。',
          steps: [
            '检查 API Base URL',
            '确认后端服务运行中',
            '重试',
          ],
          relatedCodes: ['NETWORK_DISCONNECTED'],
        },
        {
          code: 'IMPORT_INVALID_CONFIG',
          message: '导入配置时提示「无效的配置数据」',
          severity: 'warning',
          category: 'B. 配置与数据',
          location: '页面：TTS 语音导出 → 区域：顶部「导入配置」按钮',
          cause: '缺少 ttsConfig 字段。',
          solution: '确认导入 TTS 配置文件。',
          steps: [
            '用文本编辑器打开文件',
            '确认包含 "tool": "tts-export"',
            '重新导入',
          ],
          relatedCodes: ['IMPORT_INVALID_JSON'],
        },
        {
          code: 'IMPORT_INVALID_JSON',
          message: '导入配置时提示「无效的 JSON 格式」',
          severity: 'warning',
          category: 'B. 配置与数据',
          location: '页面：TTS 语音导出 → 区域：顶部「导入配置」按钮',
          cause: '文件损坏。',
          solution: '检查文件有效性。',
          steps: [
            '用文本编辑器打开文件',
            '用 JSON 格式化工具验证',
            '重新导入',
          ],
          relatedCodes: ['IMPORT_INVALID_CONFIG'],
        },
        {
          code: 'LOCAL_STORAGE_FULL',
          message: '保存失败',
          severity: 'error',
          category: 'B. 配置与数据',
          location: '页面：TTS 语音导出 → 区域：顶部「保存」按钮',
          cause: '存储空间不足。',
          solution: '清理或导出备份。',
          steps: [
            '点击「下载 JSON」备份',
            '清理 localStorage',
            '重新保存',
          ],
          relatedCodes: ['STORAGE_READ_ONLY'],
        },
        {
          code: 'STORAGE_READ_ONLY',
          message: '保存无反应',
          severity: 'critical',
          category: 'B. 配置与数据',
          location: '页面：TTS 语音导出 → 区域：顶部「保存」按钮',
          cause: '无痕模式。',
          solution: '退出无痕模式。',
          steps: [
            '确认不在无痕模式',
            '导出备份',
            '在普通窗口中重新打开',
          ],
          relatedCodes: ['LOCAL_STORAGE_FULL'],
        },
        {
          code: 'TTS_AUDIO_GENERATION_FAILED',
          message: '语音合成失败',
          severity: 'error',
          category: 'D. 模型与生成',
          location: '页面：TTS 语音导出 → 区域：左栏输出区',
          cause: '后端 TTS 服务异常。可能是模型加载失败、参考音频格式不支持、或文本包含无法合成的字符。',
          solution: '排查后端状态、参考音频和文本内容。',
          steps: [
            '检查错误详情中的具体信息',
            '如果使用了参考音频，确认格式为 WAV/MP3/OGG',
            '简化文本，移除特殊符号和表情',
            '尝试切换声音预设',
            '重试',
          ],
          relatedCodes: ['MODEL_NOT_FOUND', 'API_TIMEOUT'],
        },
        {
          code: 'TTS_REFERENCE_INVALID',
          message: '参考音频上传失败',
          severity: 'warning',
          category: 'C. 文件与输入',
          location: '页面：TTS 语音导出 → 区域：参考音频上传区',
          cause: '文件格式不支持或文件过大。',
          solution: '更换有效的音频文件。',
          steps: [
            '确认文件格式为 WAV、MP3 或 OGG',
            '确认文件大小不超过 10MB',
            '重新上传',
          ],
          relatedCodes: ['FILE_FORMAT_UNSUPPORTED', 'FILE_TOO_LARGE'],
        },
        {
          code: 'UNSAVED_WARNING',
          message: '返回首页时提示未保存',
          severity: 'info',
          category: 'B. 配置与数据',
          location: '页面：TTS 语音导出 → 区域：左上角「返回首页」按钮',
          cause: '有未保存的修改。',
          solution: '保存或放弃。',
          steps: [
            '点击「保存」',
            '或点击「确认返回」放弃',
          ],
        },
      ],
    },
    {
      id: 'paper2gal',
      title: 'paper2gal 图片素材生成',
      overview: `Paper2Gal 工具接入 p2g-character-workflow 后端工作流，负责上传角色图像并自动生成系列素材：表情图（思考、惊讶、生气）、CG 场景图和抠图素材。支持 Prompt 覆盖和 AI 并发控制，可实时查看工作流进度和下载结果。`,
      buttons: [
        { name: '选择图片', description: '上传角色图像。仅接受 PNG 和 JPG 格式，最大尺寸建议不超过 4096x4096。' },
        { name: '启动工作流', description: '向后端提交角色图像，启动 paper2gal 工作流。工作流会依次执行：验证输入、分析角色、生成表情、生成 CG、执行抠图。' },
        { name: '复制 JSON', description: '复制当前 Prompt 覆盖配置为 JSON 文本。' },
        { name: '下载 JSON', description: '下载当前配置为 JSON 文件。' },
        { name: '导出工作流 JSON', description: '下载包含工作流完整状态、步骤详情和调试信息的 JSON 文件，用于排查问题。' },
        { name: '展开 / 收起 Prompt 覆盖', description: '展开或折叠 Prompt 覆盖面板，可自定义各步骤的生成提示词。' },
        { name: '重刷', description: '清除工作流状态、上传的图片和结果，恢复为初始状态。' },
      ],
      parameters: [
        { name: '表情 Prompt 覆盖 - 思考', description: '覆盖「思考」表情生成步骤的默认 Prompt。' },
        { name: '表情 Prompt 覆盖 - 惊讶', description: '覆盖「惊讶」表情生成步骤的默认 Prompt。' },
        { name: '表情 Prompt 覆盖 - 生气', description: '覆盖「生气」表情生成步骤的默认 Prompt。' },
        { name: 'CG Prompt 覆盖 - CG01', description: '覆盖第一张 CG 场景图的生成 Prompt。' },
        { name: 'CG Prompt 覆盖 - CG02', description: '覆盖第二张 CG 场景图的生成 Prompt。' },
        { name: 'AI 并发', description: '是否允许多个 AI 生成步骤并行执行。开启后可显著缩短总耗时。', tips: '开启并发时后端会同时调度多个模型请求，但可能增加 API 费用。' },
      ],
      errors: [
        {
          code: 'API_KEY_MISSING',
          message: '启动工作流后报错，提示 API Key 未配置',
          severity: 'critical',
          category: 'A. API 与网络',
          location: '页面：paper2gal → 区域：右栏错误面板',
          cause: '未在「设置 → API」中配置 API Key。paper2gal 需要调用后端图像生成服务。',
          solution: '配置 API Key。',
          steps: [
            '打开「设置 → API」',
            '填入有效 Key',
            '保存后返回 paper2gal 重试',
          ],
          relatedCodes: ['API_KEY_EXPIRED'],
        },
        {
          code: 'API_KEY_EXPIRED',
          message: '请求返回 401',
          severity: 'critical',
          category: 'A. API 与网络',
          location: '页面：paper2gal → 区域：右栏错误面板',
          cause: 'Key 过期。',
          solution: '更换 Key。',
          steps: [
            '打开「设置 → API」',
            '替换为新的 Key',
            '保存后重试',
          ],
          relatedCodes: ['API_KEY_MISSING'],
        },
        {
          code: 'API_TIMEOUT',
          message: '工作流长时间无响应',
          severity: 'error',
          category: 'A. API 与网络',
          location: '页面：paper2gal → 区域：右栏进度条 / 错误面板',
          cause: '某个步骤耗时过长。可能是图像尺寸过大、模型负载高。',
          solution: '检查网络或稍后重试。',
          steps: [
            '等待 2~3 分钟，看是否有进度更新',
            '检查网络连接',
            '如果卡在某一长时间步骤，可在该步骤的卡片上点击「重做」单独重试',
          ],
          relatedCodes: ['NETWORK_DISCONNECTED'],
        },
        {
          code: 'BACKEND_UNAVAILABLE',
          message: '提示后端不可用',
          severity: 'critical',
          category: 'A. API 与网络',
          location: '页面：paper2gal → 区域：右栏错误面板',
          cause: '后端未启动或配置错误。',
          solution: '检查后端状态。',
          steps: [
            '检查 API Base URL',
            '确认后端服务运行中',
            '重试',
          ],
          relatedCodes: ['NETWORK_DISCONNECTED'],
        },
        {
          code: 'FILE_FORMAT_UNSUPPORTED',
          message: '上传时提示不支持的格式',
          severity: 'warning',
          category: 'C. 文件与输入',
          location: '页面：paper2gal → 区域：左栏「选择图片」按钮',
          cause: '选择了 WEBP、GIF 等不支持的格式。',
          solution: '转换为 PNG/JPG。',
          steps: [
            '使用图片转换工具转为 PNG 或 JPG',
            '重新上传',
          ],
          relatedCodes: ['UPLOAD_FORMAT'],
        },
        {
          code: 'FILE_TOO_LARGE',
          message: '上传后预览失败或工作流报错',
          severity: 'warning',
          category: 'C. 文件与输入',
          location: '页面：paper2gal → 区域：左栏预览区',
          cause: '图片过大。',
          solution: '缩小图片。',
          steps: [
            '使用图片转换工具将最大边缩放到 2048 以下',
            '重新上传',
          ],
          relatedCodes: ['DEVICE_MEMORY_LOW'],
        },
        {
          code: 'MODEL_NOT_FOUND',
          message: '工作流某步骤报错，提示模型不可用',
          severity: 'error',
          category: 'D. 模型与生成',
          location: '页面：paper2gal → 区域：右栏步骤卡片 / 错误面板',
          cause: '后端配置的模型不存在或 Key 无权访问。',
          solution: '切换模型或联系后端管理员。',
          steps: [
            '查看错误面板中的具体步骤和模型信息',
            '联系后端管理员确认模型配置',
            '如果某一步骤持续失败，可在该步骤卡片上点击「重做」尝试',
          ],
          relatedCodes: ['API_KEY_EXPIRED'],
        },
        {
          code: 'P2G_WORKFLOW_ERROR',
          message: '错误面板上显示「P2G_WORKFLOW_ERROR」',
          severity: 'error',
          category: 'E. 工作流与转换',
          location: '页面：paper2gal → 区域：右栏错误面板',
          cause: 'Paper2Gal 工作流某个步骤执行失败。可能是输入验证失败、模型不可用、API Key 失效、生成内容被安全过滤器拦截、或网络中断。',
          solution: '根据错误详情逐步排查。',
          steps: [
            '展开错误面板，阅读「可读错误信息」「可能原因」「修复提示」',
            '检查上传的图片是否为有效的 PNG/JPG',
            '检查网络连接',
            '如果提示「内容策略违规」，修改 Prompt 覆盖中的敏感词汇',
            '确认后端服务正常运行',
            '如果某一步骤失败，可在步骤卡片上点击「重做」单独重试该步骤',
            '如果整个工作流失败，点击「重刷」清除后重新开始',
          ],
          relatedCodes: ['API_KEY_MISSING', 'API_KEY_EXPIRED', 'MODEL_NOT_FOUND', 'PROMPT_BLOCKED', 'STYLE_TRANSFER_REQUEST_FAILED'],
        },
        {
          code: 'PROMPT_BLOCKED',
          message: '某步骤报错，提示内容策略违规',
          severity: 'error',
          category: 'D. 模型与生成',
          location: '页面：paper2gal → 区域：右栏步骤卡片 / 错误面板',
          cause: 'Prompt 覆盖中的内容被后端安全过滤器拦截。',
          solution: '修改 Prompt 覆盖。',
          steps: [
            '在左栏展开「Prompt 覆盖」面板',
            '找到报错的步骤对应的 Prompt',
            '移除或替换可能触发过滤器的词汇',
            '在该步骤卡片上点击「重做」',
          ],
          relatedCodes: ['P2G_WORKFLOW_ERROR'],
        },
        {
          code: 'UPLOAD_FORMAT',
          message: '上传时提示「仅支持 PNG / JPG」',
          severity: 'warning',
          category: 'C. 文件与输入',
          location: '页面：paper2gal → 区域：左栏「选择图片」按钮',
          cause: '选择了 WEBP、GIF 等格式。',
          solution: '转换格式。',
          steps: [
            '使用图片转换工具转为 PNG 或 JPG',
            '重新上传',
          ],
          relatedCodes: ['FILE_FORMAT_UNSUPPORTED'],
        },
        {
          code: 'WORKFLOW_CANCELLED',
          message: '工作流状态显示为已取消',
          severity: 'info',
          category: 'E. 工作流与转换',
          location: '页面：paper2gal → 区域：右栏进度区',
          cause: '用户手动取消了工作流，或后端因资源限制主动取消了任务。',
          solution: '重新启动工作流。',
          steps: [
            '确认是否是自己点击了取消',
            '如果不是，可能是后端资源不足',
            '等待几分钟后重新点击「启动工作流」',
          ],
          relatedCodes: ['P2G_WORKFLOW_ERROR'],
        },
        {
          code: 'WORKFLOW_STEP_FAILED',
          message: '某个步骤卡片显示为「失败」状态',
          severity: 'error',
          category: 'E. 工作流与转换',
          location: '页面：paper2gal → 区域：右栏步骤列表',
          cause: '该具体步骤执行时出错。',
          solution: '查看步骤详情并单独重试。',
          steps: [
            '点击失败步骤卡片查看错误详情',
            '根据错误信息排查（如修改 Prompt、检查网络、更换模型）',
            '点击该步骤卡片上的「重做」按钮单独重试',
            '如果多次重试仍失败，联系后端管理员',
          ],
          relatedCodes: ['P2G_WORKFLOW_ERROR', 'PROMPT_BLOCKED'],
        },
        {
          code: '429_TOO_MANY_REQUESTS',
          message: '提示请求过于频繁',
          severity: 'warning',
          category: 'A. API 与网络',
          location: '页面：paper2gal → 区域：右栏错误面板',
          cause: '工作流并发执行时发送了过多请求。',
          solution: '关闭 AI 并发或等待后重试。',
          steps: [
            '在左栏关闭「AI 并发」开关',
            '等待 1~2 分钟',
            '重新启动工作流',
          ],
          relatedCodes: ['API_RATE_LIMIT'],
        },
        {
          code: '500_INTERNAL_ERROR',
          message: '后端返回 500',
          severity: 'error',
          category: '0~9. HTTP 状态码',
          location: '页面：paper2gal → 区域：右栏错误面板',
          cause: '后端内部异常。',
          solution: '稍后重试。',
          steps: [
            '等待 2 分钟',
            '降低上传图片尺寸',
            '重试',
          ],
          relatedCodes: ['502_BAD_GATEWAY', '503_SERVICE_UNAVAILABLE'],
        },
        {
          code: '502_BAD_GATEWAY',
          message: '后端返回 502',
          severity: 'error',
          category: '0~9. HTTP 状态码',
          location: '页面：paper2gal → 区域：右栏错误面板',
          cause: '反向代理无法连接后端。',
          solution: '检查后端状态。',
          steps: [
            '确认后端进程运行中',
            '重启后端',
            '重试',
          ],
          relatedCodes: ['503_SERVICE_UNAVAILABLE'],
        },
        {
          code: '503_SERVICE_UNAVAILABLE',
          message: '后端返回 503',
          severity: 'error',
          category: '0~9. HTTP 状态码',
          location: '页面：paper2gal → 区域：右栏错误面板',
          cause: '后端暂时不可用。',
          solution: '稍后重试。',
          steps: [
            '等待 2~3 分钟',
            '重试',
          ],
          relatedCodes: ['502_BAD_GATEWAY'],
        },
      ],
    },
    {
      id: 'image-converter',
      title: '图片格式转换',
      overview: `图片格式转换是一个纯前端工具，用于上传图片并转换为 PNG 或 JPG 格式。支持亮度、对比度、饱和度、模糊、色相旋转、灰度六大滤镜调整，可控制输出质量和最大尺寸，支持保持原始宽高比。所有处理在浏览器本地完成，不会上传图片到任何服务器。`,
      buttons: [
        { name: '选择图片', description: '上传图片文件。支持 PNG、JPG 和 WEBP 格式。' },
        { name: '转换', description: '应用所有滤镜参数并生成输出图片。处理完全在浏览器本地完成。' },
        { name: '下载结果', description: '将转换后的图片下载到本地。文件名格式为 converted-{timestamp}.{ext}。' },
        { name: '复制日志', description: '将右侧日志面板的内容复制到剪贴板。' },
        { name: '下载日志', description: '将日志内容下载为文本文件。' },
        { name: '重刷', description: '清除上传的图片和结果，将所有滤镜参数重置为默认值。' },
      ],
      parameters: [
        { name: '输出格式', description: '输出图片的 MIME 类型：image/png 或 image/jpeg。', tips: 'PNG 支持透明通道但文件较大；JPG 文件小但不支持透明。' },
        { name: '质量', description: 'JPG 输出的压缩质量，范围 10~100。仅对 JPG 格式生效。', tips: '90~95 是画质和文件大小的最佳平衡点。' },
        { name: '最大宽度', description: '输出图片的最大宽度（像素）。如果原始图片更宽则会等比缩小。', tips: '设为 2048 可满足大多数社交平台的上传要求。' },
        { name: '最大高度', description: '输出图片的最大高度（像素）。', tips: '通常与最大宽度配合使用，保持宽高比开启时以较小边为准。' },
        { name: '保持宽高比', description: '缩放时是否保持原始宽高比。', tips: '建议始终开启，避免图片变形。' },
        { name: '亮度', description: '调整图片整体亮度，范围 0~200，100 为原始亮度。', tips: '低于 50 会明显变暗，高于 150 可能过曝丢失细节。' },
        { name: '对比度', description: '调整图片对比度，范围 0~200，100 为原始对比度。', tips: '值越高明暗反差越强烈，适合增强线条感。' },
        { name: '饱和度', description: '调整颜色鲜艳程度，范围 0~200，100 为原始饱和度。', tips: '设为 0 可得黑白图片；超过 150 可能出现色偏。' },
        { name: '模糊', description: '添加高斯模糊效果，范围 0~20 像素。', tips: '用于柔化背景或创建景深效果。' },
        { name: '色相旋转', description: '旋转图片整体色相，范围 0~360 度。', tips: '180 度可得到近似负片效果。' },
        { name: '灰度', description: '将图片转为灰度的强度，范围 0~100。', tips: '100 为完全黑白；0 为原始彩色。与饱和度为 0 的效果类似但算法不同。' },
      ],
      errors: [
        {
          code: 'CONVERT_ERROR',
          message: '错误面板上显示「CONVERT_ERROR」',
          severity: 'error',
          category: 'E. 工作流与转换',
          location: '页面：图片格式转换 → 区域：右栏错误面板',
          cause: '图片转换过程中发生异常。可能是源图片损坏、浏览器 Canvas 2D filter 不支持、或内存不足。',
          solution: '排查图片和浏览器兼容性。',
          steps: [
            '确认源图片能在浏览器正常打开',
            '尝试刷新页面后重新上传',
            '检查图片是否过大',
            '逐个关闭滤镜排查不支持的滤镜',
            '尝试换用其他浏览器',
          ],
          relatedCodes: ['FILE_CORRUPTED', 'DEVICE_MEMORY_LOW'],
        },
        {
          code: 'CONVERT_FILTER_UNSUPPORTED',
          message: '应用某些滤镜后输出结果异常（如全黑/全白）',
          severity: 'warning',
          category: 'E. 工作流与转换',
          location: '页面：图片格式转换 → 区域：中央预览区 / 右栏错误面板',
          cause: '当前浏览器对 Canvas 2D filter 属性支持不完整。Safari 和某些旧版浏览器对 filter 的支持有已知问题。',
          solution: '关闭不支持的滤镜或换用浏览器。',
          steps: [
            '将所有滤镜值重置为默认值（亮度/对比度/饱和度=100，模糊/色相旋转/灰度=0）',
            '逐个开启滤镜测试，找出导致异常的滤镜',
            '关闭有问题的滤镜',
            '或换用 Chrome/Firefox 等支持完整的浏览器',
          ],
          relatedCodes: ['CONVERT_ERROR'],
        },
        {
          code: 'DEVICE_MEMORY_LOW',
          message: '转换时浏览器卡死或崩溃',
          severity: 'critical',
          category: 'F. 系统与权限',
          location: '页面：图片格式转换 → 区域：整个页面',
          cause: '处理超大图片时浏览器内存不足。',
          solution: '缩小图片或关闭其他标签页。',
          steps: [
            '关闭其他浏览器标签页',
            '降低「最大宽度」和「最大高度」值',
            '刷新页面后重新上传',
          ],
          relatedCodes: ['FILE_TOO_LARGE'],
        },
        {
          code: 'FILE_CORRUPTED',
          message: '上传后预览空白',
          severity: 'warning',
          category: 'C. 文件与输入',
          location: '页面：图片格式转换 → 区域：左栏预览区',
          cause: '图片损坏。',
          solution: '更换图片。',
          steps: [
            '在系统查看器中确认图片可正常打开',
            '重新下载或导出图片',
            '重新上传',
          ],
          relatedCodes: ['CONVERT_ERROR'],
        },
        {
          code: 'FILE_FORMAT_UNSUPPORTED',
          message: '上传后无反应',
          severity: 'warning',
          category: 'C. 文件与输入',
          location: '页面：图片格式转换 → 区域：左栏「选择图片」按钮',
          cause: '选择了不支持的格式（如 SVG、PSD）。',
          solution: '转换为支持的格式。',
          steps: [
            '使用图片编辑工具导出为 PNG/JPG/WEBP',
            '重新上传',
          ],
          relatedCodes: ['FILE_CORRUPTED'],
        },
        {
          code: 'FILE_TOO_LARGE',
          message: '转换时卡顿或崩溃',
          severity: 'warning',
          category: 'C. 文件与输入',
          location: '页面：图片格式转换 → 区域：左栏预览区',
          cause: '图片尺寸过大。',
          solution: '缩小图片。',
          steps: [
            '使用其他工具将图片最大边缩放到 4096 以下',
            '重新上传',
          ],
          relatedCodes: ['DEVICE_MEMORY_LOW'],
        },
        {
          code: 'IMPORT_INVALID_JSON',
          message: '导入配置时提示「无效的 JSON 格式」',
          severity: 'warning',
          category: 'B. 配置与数据',
          location: '页面：图片格式转换 → 区域：顶部「导入配置」按钮',
          cause: '文件损坏。',
          solution: '检查文件。',
          steps: [
            '用文本编辑器打开文件',
            '确认包含 "tool": "image-converter"',
            '重新导入',
          ],
          relatedCodes: ['IMPORT_TOOL_MISMATCH'],
        },
        {
          code: 'IMPORT_TOOL_MISMATCH',
          message: '导入配置时提示「工具类型不匹配」',
          severity: 'warning',
          category: 'B. 配置与数据',
          location: '页面：图片格式转换 → 区域：顶部「导入配置」按钮',
          cause: 'tool 字段不正确。',
          solution: '确认导入正确的文件。',
          steps: [
            '用文本编辑器打开文件',
            '确认 tool 字段值为 "image-converter"',
            '重新导入',
          ],
          relatedCodes: ['IMPORT_INVALID_JSON'],
        },
        {
          code: 'STORAGE_READ_ONLY',
          message: '保存无反应',
          severity: 'critical',
          category: 'B. 配置与数据',
          location: '页面：图片格式转换 → 区域：顶部保存相关按钮',
          cause: '无痕模式。',
          solution: '退出无痕模式。',
          steps: [
            '确认不在无痕模式',
            '导出配置到文件备份',
          ],
          relatedCodes: ['LOCAL_STORAGE_FULL'],
        },
        {
          code: 'LOCAL_STORAGE_FULL',
          message: '保存失败',
          severity: 'error',
          category: 'B. 配置与数据',
          location: '页面：图片格式转换 → 区域：顶部保存相关按钮',
          cause: '存储空间不足。',
          solution: '清理或导出。',
          steps: [
            '导出当前配置到文件',
            '清理 localStorage',
            '重新保存',
          ],
          relatedCodes: ['STORAGE_READ_ONLY'],
        },
        {
          code: 'UNSAVED_WARNING',
          message: '刷新页面时弹出未保存警告',
          severity: 'info',
          category: 'B. 配置与数据',
          location: '页面：图片格式转换 → 区域：整个页面',
          cause: '参数被修改但未保存。',
          solution: '保存或放弃。',
          steps: [
            '点击保存按钮',
            '或确认放弃修改后刷新',
          ],
        },
      ],
    },
  ],
  errorDictionary: [
    {
      id: 'A',
      name: 'A. API 与网络',
      description: '涉及 API Key、网络连接、后端服务、请求超时、速率限制等外部依赖类错误。',
      errors: [
        {
          code: 'API_BASE_INVALID',
          message: '提示「API Base URL 格式不正确」',
          severity: 'critical',
          category: 'A. API 与网络',
          location: '页面：任意需联网工具 → 区域：设置面板 API 标签页',
          cause: '在「设置 → API → API Base URL」中填写的 URL 格式不正确，缺少协议头（http:// 或 https://）或包含非法字符。',
          solution: '修正 URL 格式。',
          steps: [
            '打开「设置 → API」',
            '检查 API Base URL 是否以 http:// 或 https:// 开头',
            '确保 URL 末尾没有多余斜杠或空格',
            '保存后重试',
          ],
          relatedCodes: ['BACKEND_UNAVAILABLE', 'NETWORK_DISCONNECTED'],
        },
        {
          code: 'API_KEY_EXPIRED',
          message: '请求返回 401 或提示 Key 无效/过期',
          severity: 'critical',
          category: 'A. API 与网络',
          location: '页面：任意需联网工具（转画风 / LLM / TTS / paper2gal）→ 区域：错误面板或输出区',
          cause: '配置的 API Key 已过期、被吊销、或额度已用完。',
          solution: '更换有效的 API Key。',
          steps: [
            '打开「设置 → API」面板',
            '删除当前 Key，填入新的有效 Key',
            '如果不确定 Key 是否有效，可在 LLM Hub 的实时测试面板中先测试',
            '保存后返回对应工具重试',
          ],
          relatedCodes: ['API_KEY_MISSING', '401_UNAUTHORIZED'],
        },
        {
          code: 'API_KEY_MISSING',
          message: '点击开始/发送/生成后立刻报错，提示 API Key 未配置',
          severity: 'critical',
          category: 'A. API 与网络',
          location: '页面：任意需联网工具 → 区域：错误面板或输出区',
          cause: '未在「设置 → API」中配置 API Key。所有需要调用后端服务的工具都需要有效的 API Key。',
          solution: '在设置面板中配置有效的 API Key。',
          steps: [
            '点击右上角「打开设置」或按对应快捷键',
            '切换到「API」标签页',
            '在「API Key」输入框中填入你的有效 Key',
            '点击「保存」后关闭设置面板',
            '返回工具页面重新操作',
          ],
          relatedCodes: ['API_KEY_EXPIRED', '401_UNAUTHORIZED'],
        },
        {
          code: 'API_RATE_LIMIT',
          message: '提示「Rate limit exceeded」或请求被拒绝',
          severity: 'warning',
          category: 'A. API 与网络',
          location: '页面：任意需联网工具 → 区域：错误面板',
          cause: '短时间内发送了过多请求，超过了服务商的速率限制。不同的 API 套餐有不同的速率限制。',
          solution: '等待一段时间后重试，或降低请求频率。',
          steps: [
            '查看错误详情中的 Retry-After 提示（如果有）',
            '等待 30~60 秒后重试',
            '如果频繁遇到此问题，降低同时进行的操作数量',
            '考虑升级 API 套餐以获得更高的速率限制',
          ],
          relatedCodes: ['429_TOO_MANY_REQUESTS'],
        },
        {
          code: 'API_TIMEOUT',
          message: '请求长时间无响应，最终提示超时',
          severity: 'error',
          category: 'A. API 与网络',
          location: '页面：任意需联网工具 → 区域：错误面板 / 进度条',
          cause: '后端处理耗时过长，超过了前端设置的超时时间。可能原因：请求数据量过大、模型负载高、网络延迟高。',
          solution: '降低请求规模或增加超时时间。',
          steps: [
            '降低图像尺寸、Max Tokens 或待合成文本长度',
            '增加超时设置值',
            '检查网络连接是否稳定',
            '如果使用的是自定义 API，确认后端服务器状态正常',
            '重试',
          ],
          relatedCodes: ['NETWORK_TIMEOUT', 'BACKEND_UNAVAILABLE'],
        },
        {
          code: 'BACKEND_UNAVAILABLE',
          message: '提示「后端不可用」「无法连接到服务器」或请求无法发出',
          severity: 'critical',
          category: 'A. API 与网络',
          location: '页面：任意需联网工具 → 区域：错误面板',
          cause: '后端服务器未启动、崩溃、或前端配置的 API Base URL 不正确。',
          solution: '检查后端服务状态和 API 配置。',
          steps: [
            '打开浏览器开发者工具 → Network 标签页',
            '重新操作，观察请求是否发出以及响应状态码',
            '如果请求未发出，检查「设置 → API → API Base URL」是否正确',
            '如果请求返回 502/503，联系后端管理员确认服务状态',
            '如果是本地部署，确认后端进程是否在运行（npm start）',
          ],
          relatedCodes: ['NETWORK_DISCONNECTED', '502_BAD_GATEWAY', '503_SERVICE_UNAVAILABLE'],
        },
        {
          code: 'NETWORK_DISCONNECTED',
          message: '提示网络断开或无法访问互联网',
          severity: 'critical',
          category: 'A. API 与网络',
          location: '页面：任意需联网工具 → 区域：错误面板',
          cause: '设备未连接网络、Wi-Fi 断开、或防火墙阻止了请求。',
          solution: '恢复网络连接。',
          steps: [
            '检查设备的网络连接状态',
            '尝试访问其他网站确认网络是否正常',
            '如果使用代理/VPN，检查代理设置是否正确',
            '如果是公司/校园网络，确认是否限制了 API 访问',
          ],
          relatedCodes: ['BACKEND_UNAVAILABLE', 'API_TIMEOUT'],
        },
        {
          code: 'NETWORK_TIMEOUT',
          message: '网络请求超时（与 API_TIMEOUT 区别：此错误由浏览器网络层触发）',
          severity: 'error',
          category: 'A. API 与网络',
          location: '页面：任意需联网工具 → 区域：错误面板',
          cause: '浏览器底层网络连接超时。通常发生在网络极其不稳定或完全断开的情况下。',
          solution: '检查网络连接并重试。',
          steps: [
            '确认网络连接正常',
            '如果使用 Wi-Fi，尝试靠近路由器',
            '切换到有线网络或手机热点测试',
            '重试',
          ],
          relatedCodes: ['NETWORK_DISCONNECTED', 'API_TIMEOUT'],
        },
      ],
    },
    {
      id: 'B',
      name: 'B. 配置与数据',
      description: '涉及配置文件导入导出、localStorage 存储、数据损坏、未保存警告等。',
      errors: [
        {
          code: 'CONFIG_CORRUPTED',
          message: '配置加载异常，界面显示不完整或功能无法使用',
          severity: 'error',
          category: 'B. 配置与数据',
          location: '页面：任意工具 → 区域：整个页面或特定功能区',
          cause: '浏览器 localStorage 中保存的配置数据损坏，可能由浏览器更新、手动清理数据、或跨版本导入不兼容的配置导致。',
          solution: '重置配置并清理 localStorage。',
          steps: [
            '点击页面上的「重刷」按钮',
            '在弹出的确认弹窗中点击确认',
            '如果仍然异常，按 Ctrl+Shift+I 打开开发者工具 → Application → Local Storage',
            '删除对应工具的存储键',
            '刷新页面后重新开始',
          ],
          relatedCodes: ['IMPORT_INVALID_JSON', 'STORAGE_READ_ONLY'],
        },
        {
          code: 'IMPORT_INVALID_CONFIG',
          message: '导入配置时提示「无效的配置数据」',
          severity: 'warning',
          category: 'B. 配置与数据',
          location: '页面：任意工具 → 区域：「导入配置」按钮',
          cause: '导入的 JSON 中缺少必要的配置字段（如 llmConfig、ttsConfig）或格式不正确。',
          solution: '确认导入的是正确工具的配置文件。',
          steps: [
            '用文本编辑器打开文件',
            '确认包含正确的 tool 字段和配置对象',
            '重新导入正确的文件',
          ],
          relatedCodes: ['IMPORT_INVALID_JSON', 'IMPORT_TOOL_MISMATCH'],
        },
        {
          code: 'IMPORT_INVALID_JSON',
          message: '导入配置时提示「无效的 JSON 格式」',
          severity: 'warning',
          category: 'B. 配置与数据',
          location: '页面：任意工具 → 区域：「导入配置」按钮',
          cause: '文件内容损坏、不是 JSON 格式、或被其他程序修改过。',
          solution: '检查文件是否为有效的 UTF-8 编码文本文件。',
          steps: [
            '用文本编辑器打开要导入的 JSON 文件',
            '确认文件是有效的 UTF-8 编码，无乱码',
            '用 JSON 在线格式化工具验证',
            '如果文件损坏，尝试从历史备份中恢复',
          ],
          relatedCodes: ['IMPORT_TOOL_MISMATCH', 'CONFIG_CORRUPTED'],
        },
        {
          code: 'IMPORT_TOOL_MISMATCH',
          message: '导入配置时提示「工具类型不匹配」',
          severity: 'warning',
          category: 'B. 配置与数据',
          location: '页面：任意工具 → 区域：「导入配置」按钮',
          cause: '导入的 JSON 文件中 tool 字段与当前页面不匹配。',
          solution: '确认导入的是当前工具导出的配置文件。',
          steps: [
            '用文本编辑器打开要导入的 JSON 文件',
            '确认文件顶部的 tool 字段与当前工具一致',
            '如果不是，找到正确的配置文件再导入',
            '或从其他工具页面导入该文件',
          ],
          relatedCodes: ['IMPORT_INVALID_JSON'],
        },
        {
          code: 'LOCAL_STORAGE_FULL',
          message: '保存失败，提示浏览器存储空间不足',
          severity: 'error',
          category: 'B. 配置与数据',
          location: '页面：任意工具 → 区域：「保存」按钮',
          cause: '浏览器 localStorage 存储空间已满（通常约 5~10MB）。可能保存了大量图片数据或其他工具的历史记录。',
          solution: '清理浏览器存储空间或导出配置到本地文件。',
          steps: [
            '先点击「导出」按钮将当前配置备份到本地文件',
            '按 Ctrl+Shift+I 打开开发者工具 → Application → Local Storage',
            '删除不再需要的键（尤其是包含图片 base64 的大键）',
            '返回工具重新点击保存',
          ],
          relatedCodes: ['STORAGE_READ_ONLY'],
        },
        {
          code: 'STORAGE_READ_ONLY',
          message: '保存操作无反应，刷新后数据丢失',
          severity: 'critical',
          category: 'B. 配置与数据',
          location: '页面：任意工具 → 区域：「保存」按钮',
          cause: '浏览器处于隐私/无痕模式，或 localStorage 被系统策略禁用，或磁盘空间已满导致浏览器将存储设为只读。',
          solution: '退出隐私模式或释放磁盘空间。',
          steps: [
            '确认浏览器不在无痕/隐私浏览模式（该模式通常禁用 localStorage）',
            '检查系统磁盘空间是否已满',
            '尝试在普通窗口中重新打开应用',
            '如果问题持续，使用「导出」功能将配置保存为本地文件作为替代方案',
          ],
          relatedCodes: ['LOCAL_STORAGE_FULL'],
        },
        {
          code: 'UNSAVED_WARNING',
          message: '返回首页或刷新时提示「你还没保存」',
          severity: 'info',
          category: 'B. 配置与数据',
          location: '页面：任意工具 → 区域：「返回首页」按钮 / 刷新页面时',
          cause: '当前状态与上次保存的快照不一致（isDirty 为 true）。你可能修改了内容但忘记保存。',
          solution: '根据需要选择保存或放弃。',
          steps: [
            '如果希望保留修改：点击弹窗中的「取消」或「继续编辑」，回到工具点击「保存」，然后再返回',
            '如果不需要保留：点击弹窗中的「确认返回」',
          ],
        },
      ],
    },
    {
      id: 'C',
      name: 'C. 文件与输入',
      description: '涉及图片/音频文件上传、格式不支持、文件损坏、文件过大等输入类错误。',
      errors: [
        {
          code: 'FILE_CORRUPTED',
          message: '上传后预览显示空白或损坏，或处理时报错',
          severity: 'warning',
          category: 'C. 文件与输入',
          location: '页面：任意涉及上传的工具 → 区域：预览区',
          cause: '文件本身已损坏，或下载过程中数据不完整。',
          solution: '使用其他文件或修复/重新下载该文件。',
          steps: [
            '尝试在系统默认程序中打开该文件，确认是否能正常显示/播放',
            '如果无法打开，尝试用修复工具或重新下载/导出',
            '更换为其他有效的文件',
          ],
          relatedCodes: ['FILE_FORMAT_UNSUPPORTED'],
        },
        {
          code: 'FILE_FORMAT_UNSUPPORTED',
          message: '上传时提示「不支持的文件格式」',
          severity: 'warning',
          category: 'C. 文件与输入',
          location: '页面：任意涉及上传的工具 → 区域：「选择文件」按钮',
          cause: '选择了工具不支持的文件格式。',
          solution: '将文件转换为支持的格式。',
          steps: [
            '查看工具支持的格式列表（通常在按钮下方有提示）',
            '使用图片/音频转换工具将文件转为支持的格式',
            '或使用系统自带的预览/编辑工具导出为支持的格式',
            '重新上传转换后的文件',
          ],
          relatedCodes: ['FILE_CORRUPTED', 'UPLOAD_FORMAT'],
        },
        {
          code: 'FILE_TOO_LARGE',
          message: '上传后预览失败或处理时报内存错误',
          severity: 'warning',
          category: 'C. 文件与输入',
          location: '页面：任意涉及上传的工具 → 区域：预览区',
          cause: '上传的文件尺寸过大（超过工具或浏览器限制）。',
          solution: '压缩或缩小文件后再上传。',
          steps: [
            '使用图片/音频转换工具将文件压缩或缩小尺寸',
            '对于图片，将最大边缩放到 2048 或 4096 像素以下',
            '对于音频，降低采样率或比特率',
            '重新上传处理后的文件',
          ],
          relatedCodes: ['DEVICE_MEMORY_LOW', 'FILE_FORMAT_UNSUPPORTED'],
        },
        {
          code: 'TTS_REFERENCE_INVALID',
          message: '参考音频上传失败',
          severity: 'warning',
          category: 'C. 文件与输入',
          location: '页面：TTS 语音导出 → 区域：参考音频上传区',
          cause: '文件格式不支持（仅支持 WAV/MP3/OGG）或文件过大（超过 10MB）。',
          solution: '更换有效的音频文件。',
          steps: [
            '确认音频文件格式为 WAV、MP3 或 OGG',
            '确认文件大小不超过 10MB',
            '重新上传',
          ],
          relatedCodes: ['FILE_FORMAT_UNSUPPORTED', 'FILE_TOO_LARGE'],
        },
        {
          code: 'UPLOAD_FORMAT',
          message: '上传时提示格式限制',
          severity: 'warning',
          category: 'C. 文件与输入',
          location: '页面：paper2gal / 转画风 → 区域：「选择图片」按钮',
          cause: '选择了 WEBP、GIF、BMP 等不支持的格式。这些工具仅支持 PNG 和 JPG。',
          solution: '转换为 PNG 或 JPG。',
          steps: [
            '使用图片转换工具（主页 → 图片格式转换）将文件转为 PNG 或 JPG',
            '或使用系统自带的图片预览/编辑工具导出为 PNG/JPG',
            '重新上传转换后的文件',
          ],
          relatedCodes: ['FILE_FORMAT_UNSUPPORTED'],
        },
      ],
    },
    {
      id: 'D',
      name: 'D. 模型与生成',
      description: '涉及 AI 模型不可用、内容安全过滤、Prompt 过长、生成失败等。',
      errors: [
        {
          code: 'LLM_MODEL_UNAVAILABLE',
          message: '提示模型不可用',
          severity: 'error',
          category: 'D. 模型与生成',
          location: '页面：LLM 文本接入 → 区域：实时测试面板输出区',
          cause: '选择的模型在后端不存在或当前 Key 无权访问。',
          solution: '切换其他模型。',
          steps: [
            '在「模型」下拉框中选择其他模型',
            '确认模型 ID 拼写正确',
            '确认当前 Key 支持所选模型',
            '重试',
          ],
          relatedCodes: ['MODEL_NOT_FOUND', '403_FORBIDDEN'],
        },
        {
          code: 'LLM_TEST_ERROR',
          message: '实时测试面板显示错误',
          severity: 'error',
          category: 'D. 模型与生成',
          location: '页面：LLM 文本接入 → 区域：实时测试面板输出区',
          cause: 'API 请求失败。可能是网络问题、API Key 无效或过期、模型不可用、或请求超时。',
          solution: '根据错误详情排查。',
          steps: [
            '查看错误面板中的详细错误信息',
            '检查网络连接',
            '确认 API Key 有效',
            '尝试切换模型',
            '增加超时时间或减少 Max Tokens',
          ],
          relatedCodes: ['API_KEY_MISSING', 'API_KEY_EXPIRED', 'LLM_MODEL_UNAVAILABLE'],
        },
        {
          code: 'MODEL_NOT_FOUND',
          message: '后端返回 404，提示模型未找到',
          severity: 'error',
          category: 'D. 模型与生成',
          location: '页面：任意需联网工具 → 区域：错误面板',
          cause: '模型 ID 拼写错误或该模型已被下架。',
          solution: '更正模型 ID 或选择其他模型。',
          steps: [
            '检查「模型」输入框中的模型 ID 是否拼写正确',
            '从下拉列表中选择已知可用的模型',
            '如果使用自定义 API，查阅服务商文档确认模型列表',
            '重试',
          ],
          relatedCodes: ['LLM_MODEL_UNAVAILABLE'],
        },
        {
          code: 'PROMPT_BLOCKED',
          message: '内容被安全过滤器拦截',
          severity: 'error',
          category: 'D. 模型与生成',
          location: '页面：任意 AI 生成工具 → 区域：错误面板',
          cause: 'Prompt 中包含被平台安全策略拦截的词汇。即使是正常的艺术创作词汇，某些平台也会误判。',
          solution: '修改 Prompt，移除或替换可能触发过滤器的词汇。',
          steps: [
            '查看错误详情中的具体提示信息，找出被拦截的关键词',
            '将敏感词汇用同义词替换或删除',
            '简化 Prompt，先使用最基础的描述测试是否能通过',
            '逐步添加修饰词，找出具体触发拦截的词汇',
          ],
          relatedCodes: ['403_FORBIDDEN'],
        },
        {
          code: 'PROMPT_TOO_LONG',
          message: '提示 Prompt 超出长度限制',
          severity: 'warning',
          category: 'D. 模型与生成',
          location: '页面：转画风 / paper2gal → 区域：Prompt 输入框 / 错误面板',
          cause: 'Prompt 总长度超过了后端模型的最大输入限制。',
          solution: '缩短 Prompt 或减少附加参数。',
          steps: [
            '查看「Effective Prompt Preview」中的完整 Prompt 长度',
            '精简正面 Prompt，删除冗余描述',
            '减少高级参数的数量',
            '重试',
          ],
          relatedCodes: ['MODEL_NOT_FOUND'],
        },
        {
          code: 'TTS_AUDIO_GENERATION_FAILED',
          message: '语音合成失败',
          severity: 'error',
          category: 'D. 模型与生成',
          location: '页面：TTS 语音导出 → 区域：输出区',
          cause: '后端 TTS 服务异常。可能是模型加载失败、参考音频格式不支持、或文本包含无法合成的字符。',
          solution: '排查后端状态、参考音频和文本内容。',
          steps: [
            '检查错误详情中的具体信息',
            '如果使用了参考音频，确认格式为 WAV/MP3/OGG',
            '简化文本，移除特殊符号和表情',
            '尝试切换声音预设',
            '重试',
          ],
          relatedCodes: ['MODEL_NOT_FOUND', 'API_TIMEOUT'],
        },
      ],
    },
    {
      id: 'E',
      name: 'E. 工作流与转换',
      description: '涉及工作流执行、图片转换、步骤失败、工作流取消等。',
      errors: [
        {
          code: 'CONVERT_ERROR',
          message: '图片转换过程中发生异常',
          severity: 'error',
          category: 'E. 工作流与转换',
          location: '页面：图片格式转换 → 区域：错误面板',
          cause: '图片转换过程中发生异常。可能是源图片损坏、浏览器 Canvas 2D filter 不支持、或内存不足。',
          solution: '排查图片和浏览器兼容性。',
          steps: [
            '确认源图片能在浏览器正常打开',
            '尝试刷新页面后重新上传',
            '检查图片是否过大',
            '逐个关闭滤镜排查不支持的滤镜',
            '尝试换用其他浏览器',
          ],
          relatedCodes: ['FILE_CORRUPTED', 'DEVICE_MEMORY_LOW'],
        },
        {
          code: 'CONVERT_FILTER_UNSUPPORTED',
          message: '应用某些滤镜后输出结果异常',
          severity: 'warning',
          category: 'E. 工作流与转换',
          location: '页面：图片格式转换 → 区域：预览区 / 错误面板',
          cause: '当前浏览器对 Canvas 2D filter 属性支持不完整。',
          solution: '关闭不支持的滤镜或换用浏览器。',
          steps: [
            '将所有滤镜值重置为默认值',
            '逐个开启滤镜测试，找出导致异常的滤镜',
            '关闭有问题的滤镜',
            '或换用 Chrome/Firefox 等支持完整的浏览器',
          ],
          relatedCodes: ['CONVERT_ERROR'],
        },
        {
          code: 'P2G_WORKFLOW_ERROR',
          message: 'Paper2Gal 工作流执行失败',
          severity: 'error',
          category: 'E. 工作流与转换',
          location: '页面：paper2gal → 区域：错误面板',
          cause: '工作流某个步骤执行失败。可能是输入验证失败、模型不可用、API Key 失效、生成内容被安全过滤器拦截、或网络中断。',
          solution: '根据错误详情逐步排查。',
          steps: [
            '展开错误面板，阅读「可读错误信息」「可能原因」「修复提示」',
            '检查上传的图片是否为有效的 PNG/JPG',
            '检查网络连接',
            '如果提示「内容策略违规」，修改 Prompt 覆盖中的敏感词汇',
            '确认后端服务正常运行',
            '如果某一步骤失败，可在步骤卡片上点击「重做」单独重试该步骤',
            '如果整个工作流失败，点击「重刷」清除后重新开始',
          ],
          relatedCodes: ['API_KEY_MISSING', 'API_KEY_EXPIRED', 'MODEL_NOT_FOUND', 'PROMPT_BLOCKED'],
        },
        {
          code: 'STYLE_TRANSFER_INPUT_MISSING',
          message: '未上传图片就点击了开始',
          severity: 'warning',
          category: 'E. 工作流与转换',
          location: '页面：转画风 → 区域：错误面板',
          cause: '未上传图片，或上传后点击了「开始」但没有有效的输入文件。',
          solution: '确认已上传有效的图片文件。',
          steps: [
            '点击「选择图片」按钮',
            '在文件选择器中选择有效的 PNG/JPG 文件',
            '确认预览区显示了图片缩略图',
            '点击「开始」',
          ],
          relatedCodes: ['FILE_FORMAT_UNSUPPORTED', 'FILE_CORRUPTED'],
        },
        {
          code: 'STYLE_TRANSFER_REQUEST_FAILED',
          message: '转画风请求失败',
          severity: 'error',
          category: 'E. 工作流与转换',
          location: '页面：转画风 → 区域：错误面板',
          cause: '后端 API 请求失败。可能是网络中断、API Key 无效、模型不可用、或服务器内部错误。',
          solution: '根据错误详情排查。',
          steps: [
            '展开错误面板查看详细错误信息',
            '如果是 401：检查 API Key',
            '如果是 404：检查模型',
            '如果是 429：等待后重试',
            '如果是 500/502/503：检查后端',
            '如果是网络错误：检查网络连接',
          ],
          relatedCodes: ['API_KEY_MISSING', 'API_KEY_EXPIRED', 'MODEL_NOT_FOUND', 'BACKEND_UNAVAILABLE'],
        },
        {
          code: 'WORKFLOW_CANCELLED',
          message: '工作流被取消',
          severity: 'info',
          category: 'E. 工作流与转换',
          location: '页面：paper2gal → 区域：进度区',
          cause: '用户手动取消了工作流，或后端因资源限制主动取消了任务。',
          solution: '重新启动工作流。',
          steps: [
            '确认是否是自己点击了取消',
            '如果不是，可能是后端资源不足',
            '等待几分钟后重新点击「启动工作流」',
          ],
          relatedCodes: ['P2G_WORKFLOW_ERROR'],
        },
        {
          code: 'WORKFLOW_STEP_FAILED',
          message: '工作流某个步骤失败',
          severity: 'error',
          category: 'E. 工作流与转换',
          location: '页面：paper2gal → 区域：步骤列表',
          cause: '该具体步骤执行时出错。',
          solution: '查看步骤详情并单独重试。',
          steps: [
            '点击失败步骤卡片查看错误详情',
            '根据错误信息排查',
            '点击该步骤卡片上的「重做」按钮单独重试',
            '如果多次重试仍失败，联系后端管理员',
          ],
          relatedCodes: ['P2G_WORKFLOW_ERROR', 'PROMPT_BLOCKED'],
        },
      ],
    },
    {
      id: 'F',
      name: 'F. 系统与权限',
      description: '涉及浏览器兼容性、内存不足、权限限制、导出失败等系统级问题。',
      errors: [
        {
          code: 'DEVICE_MEMORY_LOW',
          message: '浏览器标签页崩溃、卡死或无响应',
          severity: 'critical',
          category: 'F. 系统与权限',
          location: '页面：任意工具 → 区域：整个页面',
          cause: '设备内存不足，浏览器强制终止了标签页进程。通常发生在处理超大图片或大量数据时。',
          solution: '关闭其他标签页，降低数据规模，或换用内存更大的设备。',
          steps: [
            '保存当前工作（如果有）',
            '关闭其他不用的浏览器标签页',
            '降低图片尺寸或减少数据量',
            '重启浏览器后重试',
            '如果问题持续，尝试在内存更大的设备上操作',
          ],
          relatedCodes: ['FILE_TOO_LARGE'],
        },
        {
          code: 'EXPORT_FAILED',
          message: '点击导出按钮后无反应',
          severity: 'error',
          category: 'F. 系统与权限',
          location: '页面：任意工具 → 区域：导出按钮',
          cause: '浏览器阻止了下载弹窗，或内容过大导致 Blob 生成失败。',
          solution: '检查浏览器下载设置或分批导出。',
          steps: [
            '检查浏览器是否阻止了弹窗（地址栏右侧是否有弹窗拦截提示）',
            '允许当前网站的弹窗',
            '如果内容包含大量图片，尝试先移除部分图片再导出',
            '使用「复制」功能作为临时替代方案',
          ],
          relatedCodes: ['DEVICE_MEMORY_LOW'],
        },
      ],
    },
    {
      id: '0',
      name: '0~9. HTTP 状态码',
      description: '按 HTTP 状态码分类的常见后端错误。',
      errors: [
        {
          code: '401_UNAUTHORIZED',
          message: '后端返回 401 Unauthorized',
          severity: 'critical',
          category: '0~9. HTTP 状态码',
          location: '页面：任意需联网工具 → 区域：错误面板',
          cause: 'API Key 无效、过期、或被吊销。',
          solution: '更换有效的 API Key。',
          steps: [
            '打开「设置 → API」',
            '替换为新的有效 Key',
            '保存后重试',
          ],
          relatedCodes: ['API_KEY_EXPIRED', 'API_KEY_MISSING'],
        },
        {
          code: '403_FORBIDDEN',
          message: '后端返回 403 Forbidden',
          severity: 'error',
          category: '0~9. HTTP 状态码',
          location: '页面：任意需联网工具 → 区域：错误面板',
          cause: '当前 API Key 无权访问请求的资源，或请求内容触发了平台的内容安全策略。',
          solution: '检查 Key 权限或修改请求内容。',
          steps: [
            '确认当前 Key 支持所选模型/服务',
            '如果提示内容策略违规，修改 Prompt 移除敏感词汇',
            '联系服务商确认账户状态',
          ],
          relatedCodes: ['API_KEY_EXPIRED', 'PROMPT_BLOCKED'],
        },
        {
          code: '404_NOT_FOUND',
          message: '后端返回 404 Not Found',
          severity: 'error',
          category: '0~9. HTTP 状态码',
          location: '页面：任意需联网工具 → 区域：错误面板',
          cause: '请求的 API 端点不存在。可能是 URL 配置错误、模型 ID 错误、或后端路由已变更。',
          solution: '检查 URL 和模型配置。',
          steps: [
            '检查「设置 → API → API Base URL」是否正确',
            '检查模型 ID 是否拼写正确',
            '确认后端 API 版本是否匹配',
          ],
          relatedCodes: ['MODEL_NOT_FOUND', 'API_BASE_INVALID'],
        },
        {
          code: '429_TOO_MANY_REQUESTS',
          message: '后端返回 429 Too Many Requests',
          severity: 'warning',
          category: '0~9. HTTP 状态码',
          location: '页面：任意需联网工具 → 区域：错误面板',
          cause: '短时间内发送了过多请求，超过了服务商的速率限制。',
          solution: '等待后重试。',
          steps: [
            '查看错误详情中的 Retry-After 提示',
            '等待 30~60 秒',
            '降低请求频率后重试',
          ],
          relatedCodes: ['API_RATE_LIMIT'],
        },
        {
          code: '500_INTERNAL_ERROR',
          message: '后端返回 500 Internal Server Error',
          severity: 'error',
          category: '0~9. HTTP 状态码',
          location: '页面：任意需联网工具 → 区域：错误面板',
          cause: '后端服务在处理请求时发生内部异常。可能是模型加载失败、GPU 内存不足、或代码 Bug。',
          solution: '稍后重试或联系后端管理员。',
          steps: [
            '等待 1~2 分钟后重试',
            '降低请求规模（图像尺寸、Max Tokens 等）',
            '如果问题持续，联系后端管理员查看服务器日志',
          ],
          relatedCodes: ['502_BAD_GATEWAY', '503_SERVICE_UNAVAILABLE'],
        },
        {
          code: '502_BAD_GATEWAY',
          message: '后端返回 502 Bad Gateway',
          severity: 'error',
          category: '0~9. HTTP 状态码',
          location: '页面：任意需联网工具 → 区域：错误面板',
          cause: '反向代理无法连接到后端应用服务器。可能是后端进程崩溃或未启动。',
          solution: '检查后端服务状态。',
          steps: [
            '如果是本地部署，确认后端进程是否在运行',
            '检查后端服务端口是否被占用',
            '查看后端日志确认是否有启动错误',
            '重启后端服务后重试',
          ],
          relatedCodes: ['503_SERVICE_UNAVAILABLE', 'BACKEND_UNAVAILABLE'],
        },
        {
          code: '503_SERVICE_UNAVAILABLE',
          message: '后端返回 503 Service Unavailable',
          severity: 'error',
          category: '0~9. HTTP 状态码',
          location: '页面：任意需联网工具 → 区域：错误面板',
          cause: '后端服务暂时不可用，可能正在进行维护、重启、或过载保护。',
          solution: '稍后重试。',
          steps: [
            '等待 2~3 分钟后重试',
            '检查后端服务状态页面（如果有）',
            '联系后端管理员确认是否在维护',
          ],
          relatedCodes: ['502_BAD_GATEWAY', 'BACKEND_UNAVAILABLE'],
        },
      ],
    },
  ],
};
